### ISSUE TITLE
Boxplot issue

### ISSUE THREAD

**Issue by kohry** [brightics/studio#122]
Hi, Boxplot needs to be fixed
![boxplot](https://user-images.githubusercontent.com/7043208/50257804-37accb80-0440-11e9-8655-e2c427649c2a.PNG)

As you see above, outliers are not matched with boxplots.
outliers dots should be shifted to the 1 right.

here where I get the loaded data - 
http://docs.brightics.ai/ko-kr/ai/v3.5/tutorials/15_aggregation?id=insight
[15_sns_usage_time.zip](https://github.com/brightics/studio/files/2697049/15_sns_usage_time.zip)

**Comment by iisejin** [comment]
It will be released on January 2.
