### ISSUE TITLE
groupby function in Statistic Summary

### ISSUE THREAD

**Issue by kohry** [brightics/studio#124]
Hi, 
Statistic summary function needs some upgrade - groupby
![1](https://user-images.githubusercontent.com/7043208/50263798-fc6bc600-045a-11e9-8036-7feadb68df4d.PNG)

Many of tutorials are using statistic summary with groupby function, so this will be also useful as it has been.
sample below.
![2](https://user-images.githubusercontent.com/7043208/50263860-376df980-045b-11e9-87af-118aa0135a45.PNG)

**Comment by shovsj** [comment]
Thank you for your suggestion.

Several functions recently developed, including statistic summary, needs group by parameter.
We will enhance it soon.

**Comment by kohry** [comment]
> Thank you for your suggestion.
> 
> Several functions recently developed, including statistic summary, needs group by parameter.
> We will enhance it soon.

don't forget the statistic derivation function 👍
