### ISSUE TITLE
using train result as a table (linear regression)

### ISSUE THREAD

**Issue by kohry** [brightics/studio#128]
Hi, using train output as an input in the next node is sometimes analysts do, 
but this is not available right now.

![13](https://user-images.githubusercontent.com/7043208/50327977-863b9200-0534-11e9-8500-07b35a8bd4e2.PNG)

Deriving model result as a table format is required, 
as many people are using model result as a next step train data, when they do stacking / ensembling / blending.

![14](https://user-images.githubusercontent.com/7043208/50328433-6ad18680-0536-11e9-9b05-b3df8c064ebc.PNG)

**Comment by shovsj** [comment]
We're under consideration. 
suppose that linear regression model is given as:
{
'summary':{
'table1':table1(pd.table),
 'table2':table2(pd.table)
}, ...
}
The fastest way is:
we develop a function which takes a parameter key: ['summary','table2'] 
and returns input_json['summary']['table2'] which is a pd.table.

it is somewhat similar to select columns from a given table. so one can create gui to help selection.

The other way, what I hope to be is:
![image](https://user-images.githubusercontent.com/37683852/50331755-2698b300-0543-11e9-8565-86e815d1e480.png)

@iisejin
@JaebooJung
Let me know your opinion

**Comment by shovsj** [comment]
We decided to defer this issue. We will reopen this issue or a related issue later.
