### ISSUE TITLE
Json related new functions

### ISSUE THREAD

**Issue by shovsj** [brightics/studio#142]
Flatten Json:
This function flattens json object to generate a table containing its jsonable elements.
![image](https://user-images.githubusercontent.com/37683852/50556748-7d12a800-0d20-11e9-977d-4d403c4c65f1.png)
The following result is when the input model is a grouped data.
![image](https://user-images.githubusercontent.com/37683852/50556759-a0d5ee00-0d20-11e9-830a-9f3d819b5f04.png)

Get Table:
This function generate a table from a dataframe element in some json object.
![image](https://user-images.githubusercontent.com/37683852/50556789-ed212e00-0d20-11e9-8ca6-b746c227bd31.png)

![image](https://user-images.githubusercontent.com/37683852/50556791-fe6a3a80-0d20-11e9-9048-037972a1b4be.png)

**Comment by kohry** [comment]
@shovsj 
Sorry for late reply, This is exactly what I want!
Will this be included in 8 version? 
It seems that in 7 version, Only the first table (r2 table) can be used in the next function node.
