### ISSUE TITLE
Binarizer is too slow

### ISSUE THREAD

**Issue by kohry** [brightics/studio#152]
Binarizer is very simple function, but it seems it takes more than 90sec for data with 6000 rows,
![bin](https://user-images.githubusercontent.com/7043208/50619785-b6286380-0f3e-11e9-9637-e8024e8201d4.PNG)

**Comment by shovsj** [comment]
Thank you for your contribution and support. I will check this issue and merge it soon.

**Comment by power4454** [comment]
Improved
