### ISSUE TITLE
Discretize Quantile, Transpose, One Sample T Test, Paired T Test, Binarizer, EWMA - update

### ISSUE THREAD

**Issue by seungrojoo** [brightics/studio#154]
discretize quantile: model dictionary update, code optimization
transpose : parameter name change, columns -> input_cols (module, json)
one sample ttest: model dictionary update, p-value modification, code optimization
paired ttest : model dictionary / model output update (module, json)
binarizer : output table name change, table -> out_table (module, json), code optimization
ewma : code optimization

**Comment by power4454** [comment]
Updated
