### ISSUE TITLE
I think brightics studio need some function.

### ISSUE THREAD

**Issue by elrion018** [brightics/studio#17]
as a student, There are many times to presentation results with Powerpoint of MS. so, i think it needs functions to export results to PPT as well as to report.

**Comment by JaebooJung** [comment]
OK, we will discuss it later. Thank you for the suggestion.

**Comment by shovsj** [comment]
Can I close this issue? This issue (or related other issue) will be reopened later.

**Comment by elrion018** [comment]
Of course. You will

2019년 1월 7일 (월) 오전 11:17, Sungjun Kim <notifications@github.com>님이 작성:
