### ISSUE TITLE
Studio install Guide 요청 

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#18]
Studio install Guide을 찾을 수 없네요.

어디에 있는지, 혹시 없으면 언제 받을 수 있나요?

**Comment by krazyeom** [comment]
https://github.com/brightics/studio/blob/master/README.md  

README를 참고 부탁드립니다.

**Comment by krazyeom** [comment]
@ezcyber BrighticsStudio-1.0-beta-windows.exe 를 실행하고, Brightics-Installer.cmd 를 실행해서 압축을 푸셨나요?

**Comment by ezcyber** [comment]
Download받은 후 별도의 Dir에 설치하여 문제가 해결되었습니다.

감사합니다.

**Comment by lensman86** [comment]
혹시
BrighticsStudio-1.0-beta-windows.exe 를 어디서 받을 수 있나요?

감사합니다.

**Comment by JaebooJung** [comment]
@lensman86 여기 깃헙의 release탭을 클릭하셔서 다운받으시면 됩니다. 혹은 http://www.brightics.ai/downloads 에서도 가능합니다.

**Comment by lensman86** [comment]
@JaebooJung 
감사합니다.
