### ISSUE TITLE
The first row is deleted when outputting table data to model through python script

### ISSUE THREAD

**Issue by ihk6262** [brightics/studio#20]
The first row is deleted when outputting table data to model through python script.
ex)
input : iris data 
function : python script ( df = inputs(0), out = df['sepal_length'] )
out type :  Model 
result : first row is deleted

**Comment by power4454** [comment]
solved

input : iris data
function : python script 
( 
df = inputs[0]
out = df['sepal_length']
 )
out type : Model

There is no deletion
