### ISSUE TITLE
데이타 크기에 한계가 있나요?

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#23]
Column : 4,999개, Row : 4,459를 
CSV에서 가져오는데 Load시간을 30초이내였는 데 
Table로 view하는 데 3분이상소요되면 화면도 거의 움직이지 않아요.

**Comment by ezcyber** [comment]
Fetch시간에 오래 걸리는 데  Fetch량을 조절하기 위한 기능은 
어디서 설정하나요? 
사전에 Fetch량을 조절하기 위해 Row /Col등의 설정 기능이 있으면 좋을 것 같은 데

**Comment by JaebooJung** [comment]
컬럼갯수가 많은 데이터의 경우 웹상에서 표시할때 렌더링이 오래걸려서 그런 현상이 발생합니다. Fetch량을 조절하는 기능은 저희도 공감하고 있으며, 다음버전때 포함될 수 있도록 해보겠습니다.
