### ISSUE TITLE
XGB Classification Model input선택 방법

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#25]
사용 방법이 어떻게 되나요?
화면을 들어 가면 Input변수를 선택하라고 되어 있는 데 
![xgb](https://user-images.githubusercontent.com/32014177/48685909-609d2f00-ebfc-11e8-9b5d-b899a7f2fe2b.PNG)

**Comment by shovsj** [comment]
해당 함수는 인풋을 두개를 필요로 합니다. xgb train의 결과를 해당함수의 input으로 연결해주세요.

다음 tutorial을 확인 부탁드립니다.
http://www.brightics.ai/docs/en-us/ai/v3.6/tutorials/60_py_car_accident

**Comment by ezcyber** [comment]
확인하였습니다. 
감사합니다
