### ISSUE TITLE
제조 품질 부문 관련 기능 추가 계획을 알고 싶어요

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#28]
제조 공정에 많이 사용하는 기능이 있는데 
특히, 관리도 및 공정능력 분석, 신뢰성분석등의 기능이 있습니다.

이 부분에 대한 개발 계획이 있는지 알고 싶습니다.

**Comment by JaebooJung** [comment]
저희가 업종특화 기능을 따로 개발하지는 않습니다, 다만 신뢰성분석 같은 경우는 일반적으로 쓰이는 것이라 함수로 추가할 수 있겠습니다. 그외 필요하신 함수가 있다면 toolkit 기능을 활용해서 자체적으로 추가하시는 방법이 있으니 문서를 참고해주세요.
