### ISSUE TITLE
rest api 관련 문의

### ISSUE THREAD

**Issue by IreneSSS** [brightics/studio#285]
1. rest api 요청 url 정보 알수있을까요?
2. rest api가 함수 호출하나하나에 대한 모든 api 가 있는 게 아니라 
   데이터를 public 으로 옮길떄 lightweight한 가벼운 agent하나 띄워서 외부로 보내는 용도로의 api정도만 뚫려있는 것인지요? 전체 기능 다 api가 있는거같진않은데 확인 부탁드리며 추후 개별 function api 호출 업데이트 계획이 있는지 알고싶습니다.

**Comment by krazyeom** [comment]
지금은 Studio API만 따로 뽑아놓은게 없어서, 

http://brightics.ai/kr/docs/ai/v3.6/api_guide/execute_job?type=core

페이지에서 왼쪽에서 job, jobStatus, data 3곳을 참고하시면 됩니다.
