### ISSUE TITLE
Compability with Java 9

### ISSUE THREAD

**Issue by janrenz** [brightics/studio#3]
When tring to run this on OS X with Java 9 installed, i first had to remove a log option in start_server.sh that is not supported in Java 9 anymore.
After that springs boots up, but i receive the following error:
```
03:30:51.907 ERROR [] Application startup failed - MDC:[] CLASS:[SpringApplication]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource 
```

Sadly my Java knowledge is not so good, would love a few more infos on the setup required ...

**Comment by krazyeom** [comment]
@janrenz First of all, thank you for using Brightics Studio. 
Brightics uses some opensource projects. but there are some issue in JAVA 9 or later version. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above 
So We are trying to solve that issue.

**Comment by janrenz** [comment]
Great, till then maybe a small remark in the requirements section would make sense...

**Comment by JaebooJung** [comment]
We should remove a plus symbol for the JDK version until api-server supports. Java9 has some dependency issues with Spring Boot 1.5.x. I think it is a quite simple work so we can fix it soon.

**Comment by janrenz** [comment]
Fixed with https://github.com/brightics/studio/commit/ed629f0a1d1f10b582601c0b0d4d28dc87e01fc3
