### ISSUE TITLE
Databases Essential Information

### ISSUE THREAD

**Issue by SETIADEEPANSHU** [brightics/studio#370]
What is the username and password for accessing different kind of databases stored? Please comment!
@jisujeong @freenak @krazyeom @vocatan @janrenz

**Comment by JaebooJung** [comment]
Brightics uses sqlalchemy with pandas to access databases. To establish connection we need username and password like a example below. 

    import sqlalchemy as db
    engine = db.create_engine('dialect+driver://user:pass@host:port/db')

The part of dialect means the kind of databases so you should select DB type field in Brightics Datasource Management dialog. Then brightics automatically set the proper driver for db type you selected.

**Comment by SETIADEEPANSHU** [comment]
@JaebooJung can you give the username and password for brightics_h2db.mv database file?

**Comment by JaebooJung** [comment]
@SETIADEEPANSHU You can find out it from https://github.com/brightics/studio/blob/master/api-server/brightics-server/src/main/resources/application.properties.
