### ISSUE TITLE
SAP Hana Connection 문의

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#371]
SAP Hana를 분석 마트로 활용하고 있는데 
Studio Ver.에서 부분에 대한 Driver 지원이 되는 지 확인 요청을 드립니다.
또는 ODBC로 연결을 하려면 어떻게 설정하는 지도 문의드립니다.

**Comment by hyoxt121** [comment]
Windows  명령 프롬프트에서
brightics-studio\lib\python 로 가셔서 pythoh get-pip.py를 하셔서 pip를 설치합니다.
그리고 brightics-studio\lib\python\Script 로 가셔서 pip install pyhdb를 하셔서 PyHDB를 설치합니다.
Hana DB 사용법은 https://github.com/SAP/PyHDB 에 나와있으며 script로 사용하시면 됩니다.
