### ISSUE TITLE
n gram cannot find string type column

### ISSUE THREAD

**Issue by kohry** [brightics/studio#387]
![image](https://user-images.githubusercontent.com/7043208/52915119-8af1ac00-3313-11e9-80c9-2ef001a2c9f3.png)

n gram function cannot find any column.
If it only takes string array as parameter, brightics should support tokenizer with enough explanation.

**Comment by jen-choi** [comment]
We need to discuss whether to support string type of input column or offer a tokenizer. We will support this in any way we can.

**Comment by kohry** [comment]
thanks for replying
I think, tokenizer is much better option.
Maybe some nltk libraries would help for tokenizing both Korea and English. (eunjeon, komoran, gensim, nltk, and anything would be fine)
