### ISSUE TITLE
Upload data files with multiple parts

### ISSUE THREAD

**Issue by hyunbinloh** [brightics/studio#389]
Hello, how are you?

In large data cases, data files do not consist of a single file.

For example, run the following command and we get multiple files.
df.write.format("csv").option("header", "true").save("data/mydata")

This can be loaded by
sqlContext.read.format("csv").option("header", "true").load("data/mydata)

I think there should be a way to load files with multiple part in Brightics. (csv, orc)
orc files can be saved and loaded by changing csv to orc from the upper commands.

Thanks.

**Comment by biue8765** [comment]
There is no plan to develop the function you mentioned yet.
Because we do not think there are many cases where users upload two excels at a time.
If this kind of request increases, we will consider developing the function.

**Comment by hyunbinloh** [comment]
It is completely okay not developing, but I just want to clear up the point.
orc files don't mean two excel files. A single orc file consists of the distributed parts.
For example, "iris.orc" or "iris.csv" is not a single excel file, but one file with multiple parts.
This can be seen if you save the file in the spark-shellin linux.
Thank you very much!
