### ISSUE TITLE
LDA output table is missing, and model output is slowing down Brightics.

### ISSUE THREAD

**Issue by kohry** [brightics/studio#396]
![image](https://user-images.githubusercontent.com/7043208/52953176-162d7900-33ca-11e9-941c-50f5a24330a1.png)

Hi, there is no table output for LDA.
Primary output should be table, with column 'topic' with proper topic numbering.

Current LDA tries to show all text results in the model output, so it is slowing down Brightics. Model output should show user the most important insights such as feature importance in decision tree, not the whole output.

LDA topic classification result is most likely used in the next function(sausage?), so this should be fixed.

**Comment by hyoxt121** [comment]
We will fix it as soon as possible.

**Comment by krazyeom** [comment]
resolved.
