### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by kawonni** [brightics/studio#405]
브라이틱스 182.193.17.125 접속 시,  ESOCKETTIMEDOUT 오류로 데이터 로딩이 되지 않습니다.
그리고 이건 다른 얘긴데요, 스튜디오 버전은 원래 IRIS 데이터만 사용 가능한건지 궁금합니다.

**Comment by JaebooJung** [comment]
이곳은 brightics studio 관련 이슈를 공유하는 공간이라, 사내 분석서버와 관련한 것은 메일로 문의 부탁드립니다. 

스튜디오 에서도 IRIS 이외에 다른 데이터를 사용 하실 수 있습니다. Load함수는 업로드한 데이터로써 관리되고 있는 디렉토리를 선택할 수 있는 함수이고, Read CSV는 경로를 직접 입력하여 CSV 파일을 로드 할 수 있는 기능입니다. 두 함수를 사용하시면 다른 데이터를 사용할 수 있습니다.

**Comment by kawonni** [comment]
> 이곳은 brightics studio 관련 이슈를 공유하는 공간이라, 사내 분석서버와 관련한 것은 메일로 문의 부탁드립니다.
> 
> 스튜디오 에서도 IRIS 이외에 다른 데이터를 사용 하실 수 있습니다. Load함수는 업로드한 데이터로써 관리되고 있는 디렉토리를 선택할 수 있는 함수이고, Read CSV는 경로를 직접 입력하여 CSV 파일을 로드 할 수 있는 기능입니다. 두 함수를 사용하시면 다른 데이터를 사용할 수 있습니다.

네 감사합니다 사내 담당자분께 질문 드렸습니다~
