### ISSUE TITLE
Is Windows 2012 R2 server supported for brightics?

### ISSUE THREAD

**Issue by SETIADEEPANSHU** [brightics/studio#414]
When trying on Windows 2012 R2 server, this error comes 

![image](https://user-images.githubusercontent.com/13046972/53467868-e9d6c400-3a7d-11e9-8e42-8583bc8bebe7.png)

@janrenz @krazyeom @vocatan @jisujeong @freenak

**Comment by krazyeom** [comment]
@SETIADEEPANSHU 

Could you get me the error log of detail?

We don't have a Windows 2012 R2 server right now, so we can not try to test it on a Windows 2012 Server. We just tested it on Windows 7 and Windows 10.

Brightics runs on python 3.6, we provide x86 version of Python 3.6 in Brightics. I think the Python cannot run on Windows 2012 server. 

First of all, you have to install a server version of Python on the server. 

2nd, there is `BRIGHTICS_PYTHON_PATH` property In brightics-studio\brightics-server\start-server.cmd 
You should change a location with a server version of  Python.

```
SET BRIGHTICS_PYTHON_PATH=%BRIGHTICS_HOME%\lib\python\python.exe
```
Maybe there is also something problem with python library packages. We built the library for x86 version. 
so if you would get the same error message, we cannot solve it now. 

We recommend running brightics on Windows 7 or 10.

**Comment by krazyeom** [comment]
You can also read this article. 
Python 3.6 won't install on Windows 2012 R2 :  https://bugs.python.org/issue29583

**Comment by krazyeom** [comment]
I've got the same error on Windows (Windows Server 2008 R2 Datacenter).

**Comment by krazyeom** [comment]
![image](https://user-images.githubusercontent.com/442477/65289118-6a792100-db84-11e9-9d8a-ca84f13f4e4d.png)

It works very well on  Windows (Windows Server 2008 R2 Datacenter).
