### ISSUE TITLE
How to extract time from timestamp column in csv table loaded

### ISSUE THREAD

**Issue by janrenz** [brightics/studio#467]
Hi,

I try to load a csv table that contains timestamps.  How do I tell brightens to convert  this to an internal timestamp?
I tried both with load csv and with load function.

Any help is welcome.

Jan

![Screenshot 2019-03-21 at 08 40 11](https://user-images.githubusercontent.com/224011/54738539-f4840500-4bb4-11e9-8865-656b647f5bfd.png)

**Comment by krazyeom** [comment]
![image](https://user-images.githubusercontent.com/442477/55060427-cae74400-50b4-11e9-8dec-894119aa367f.png)

We are using sqlite3 in Query Executor function. sqlite3 provides some Date And Time Functions. You can get the more information on https://www.sqlite.org/lang_datefunc.html  

ex)
SELECT date(timestamp) as YYYYMMDD  FROM #{DF(0)}

**Comment by janrenz** [comment]
Thanks, this is really helpful. I suggest that Tipps like this are added to the docs! Both to the query extractor section but also to a common how to Section.
