### ISSUE TITLE
How to extract json into columns 

### ISSUE THREAD

**Issue by janrenz** [brightics/studio#468]
Related to #467 

How do I convert a csv containing JSON data in one of the columns so I can access the values.

Thanks!

Jan

![Screenshot 2019-03-21 at 08 47 05](https://user-images.githubusercontent.com/224011/54738899-63159280-4bb6-11e9-9815-d7160ed53bce.png)

**Comment by biue8765** [comment]
The first method is to use Python Script.
Below is an example of a script.

import pandas as pd
from pandas.io.json import json_normalize
import json

colNm = 'context'
indf = inputs[0]
resdf = pd.concat([json_normalize(json.loads(indf[colNm][l])).assign(index=l) for l in indf.index]).set_index('index')

**Comment by biue8765** [comment]
Second method is to use Query Executor.

Create Query Executor function and use it as below example.
#{DF(0)} is a previous table.

json(context) as test_json
,json_extract(test,'$.k1') as k1
,json_extract(test,'$.k2') as k2
,json_extract(test,'$.k3') as k3
FROM #{DF(0)}

**Comment by shovsj** [comment]
We are using sqlite3 in Query Executor function. sqlite3 provides some sql functions managing JSON contents. Please see https://www.sqlite.org/json1.html for more information.

In this case, as bisu8765 mentioned,(I mis-deleted, sorry.) 

Create Query Executor function and use it as below example.
#{DF(0)} is a previous table.

SELECT * 
,json_extract(test,'$.k1') as k1
,json_extract(test,'$.k2') as k2
,json_extract(test,'$.k3') as k3
FROM #{DF(0)}

**Comment by krazyeom** [comment]
![image](https://user-images.githubusercontent.com/442477/55050399-d6764300-5093-11e9-8a14-7006d6cc9960.png)

You can access a value from JSON type by json_extract function in Query Executor.

SELECT *, json_extract(context,'$.screen_width') as screen_width, json_extract(context,'$.screen_height') as screen_height
FROM #{DF(0)} 

thanks, @biue8765

**Comment by janrenz** [comment]
Thank you! Like in my other ticket, I suggest to add this tips to the docs as they might be helpful for others as well (not searching here).
