### ISSUE TITLE
no image as output

### ISSUE THREAD

**Issue by kohry** [brightics/studio#477]
![image](https://user-images.githubusercontent.com/7043208/55599312-0dcea900-5792-11e9-9032-d256fa1474a2.png)

I tried to use jpeg image as an output, but it fails and never shows the image.

**Comment by JaebooJung** [comment]
It seems the current type of image is limited to matplotlib such as

    import matplotlib.pyplot as plt
    plt.plot(inputs[0]["sepal_length"],inputs[0]["sepal_width"])
    image = plt

I think it should support general purpose of image like this case. We will fix it soon, thanks for the creating the issue.

**Comment by hyoxt121** [comment]
Yes, I seem to work by using plt as above mentioned.
This is an example of showing jpg files.

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
img = mpimg.imread('C:\\apple.jpg')
imgplot = plt.imshow(img)
plt.show()

Please install proper packages through pip commend on your Studio (like Image)

![image](https://user-images.githubusercontent.com/36657450/55708695-80a18380-5a21-11e9-9af0-d30d33b21f03.png)

**Comment by hyoxt121** [comment]
Yes, it seems to work by using matplotlib as above mentioned.
This is an example of showing jpg files.

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
img = mpimg.imread('C:\\\\apple.jpg')
imgplot = plt.imshow(img)
plt.show()

Please install proper packages through pip commend on your Studio (like Image)

![image](https://user-images.githubusercontent.com/36657450/55709320-083bc200-5a23-11e9-8a9f-ee0ab1dc2cf4.png)

**Comment by hyoxt121** [comment]
Yes, it seems to work by using matplotlib as mentioned above.
This is an example of showing jpg files.

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
img = mpimg.imread('C:\\\\apple.jpg')
imgplot = plt.imshow(img)
plt.show()

Please install proper packages through pip command on your Studio (like image)
We will enhance it soon to deal with general cases.

![image](https://user-images.githubusercontent.com/36657450/55709320-083bc200-5a23-11e9-8a9f-ee0ab1dc2cf4.png)

**Comment by hyoxt121** [comment]
Yes, it seems to work by using matplotlib as mentioned above.
This is an example of showing jpg files.

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
img = mpimg.imread('C:\\\\apple.jpg')
plt.imshow(img)

Please install proper packages through pip command on your Studio (like image)
We will enhance it soon to deal with general cases.

![image](https://user-images.githubusercontent.com/36657450/55709320-083bc200-5a23-11e9-8a9f-ee0ab1dc2cf4.png)

**Comment by hyoxt121** [comment]
Yes, it seems to work by using matplotlib as mentioned above.
This is an example of showing jpg files.

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
img = mpimg.imread('C:\\\\apple.jpg')
plt.imshow(img)

Please install proper packages through pip command on your Studio (like image)
We will enhance it soon to deal with general cases.

![image](https://user-images.githubusercontent.com/36657450/55710708-2c4cd280-5a26-11e9-8409-b40310b1d064.png)
