### ISSUE TITLE
User별 Project 관리 가능한지...

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#482]
Window Server에서 설치하여 사용하려고 하는데 
접근하는 User에 따라  Project 사용 기능을 부여하려고 합니다.

이러한 기능이 지원하고 있나요?

지원하지 않으면 지원 계획이 있는지?

**Comment by biue8765** [comment]
![member management](https://user-images.githubusercontent.com/44859963/55944532-c493c300-5c83-11e9-8a3c-c1ea5af1fd01.png)

**Comment by biue8765** [comment]
Brightics Studio는 오픈소스 버전으로, 위의 기능을 제공하고 있지 않습니다.
Brightics Enterprise/Standard 버전과 같은 상용버전에서 위의 기능을 제공하고 있으니,
사용을 원하시는 경우 brightics@samsung.com계정으로 메일 보내주십시오.
