### ISSUE TITLE
feature columns of logistic regression can be array type.

### ISSUE THREAD

**Issue by power4454** [brightics/studio#487]

**Comment by shovsj** [comment]
1. This issue should be generalized to create some preprocessing module, let's say a feature_extractor.
There is a function that takes input as pd.dataframe and outputs np.array X. Basically, from dataframe
f_1| f_2| f_3
_____
--|--|--
a|1|[1,2]
b|2|[3,4]
this function may generate
[
[0, 1, 1, 2],
[1, 2, 3, 4]
]
here, i assumed that label indexing but one hot encoding is also possible, optionally.
Then all the ml estimator should use this preprocessing module for consistency.

2. Need a vector type(sparse vector): 
suppose that a column contains 1000 categories. If I one-hot encoded this column, then I get a 1000 columns additionally. This is not efficient. If the result is addition of a column containing a list of 1000 floats, this is adequate but is by no means satisfactory. if each column contains one hot index and value for the index, it would be space and also computationally efficient.
There are many examples including tf-idf, polynomial expansion also.

3. (1+2) create a preprocessing function that takes dataframe as input, and outputs
np.array X or scipy.sparse.csr_matrix depending on the dataset and column type and params the user chooses(one-hot encoding? or label indexing?)
