### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:9097

### ISSUE THREAD

**Issue by HenryPaik1** [brightics/studio#493]
I've encountered this issue when open `http://127.0.0.1:3000/`
~~~
# detail info
Error: connect ECONNREFUSED 127.0.0.1:9097
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
~~~
and terminal shows:
~~~
$ ./start-server.sh: line 29: kill: (30867) - No such process
~~~

Would you let me know how to solve this issue?

**Comment by kohry** [comment]
same issue here when trying running on mac os 10.14

**Comment by kohry** [comment]
It fails to load function first, but when reloading, it seems okay.

**Comment by JaebooJung** [comment]
This is because GUI application is started before RESTful API server. RESTful API server needs a few more seconds to start up. We already recognized it and would prepare new launcher app to manage these processes.

**Comment by CallessCaller** [comment]
Still not working.
