### ISSUE TITLE
auto (double) quotation mark removal when loading local files

### ISSUE THREAD

**Issue by kohry** [brightics/studio#507]
Several datasets on the internet have column header with double quotation mark .
Brightics cannot load them. Instead, it shows error message

This behavior is not convenient though, because user should change them manually with other editor. 

I think, if quotation marks are found in the headers, removing automatically will be better option to the  common uses. (or leave the quotation mark just a way it is, rather than showing error msg)

![image](https://user-images.githubusercontent.com/7043208/56865347-00f74b00-6a08-11e9-999d-926284190104.png)

(One more thing, excel automatically removes double quotation mark.)

**Comment by shovsj** [comment]
csv files exported by R uses this format, right? This should be fixed with the highest priority.  Thanks.

Can we change the column names in this window? if not, it is necessary also.

**Comment by hyoxt121** [comment]
We completely agree with your opinion Will fix it.

**Comment by seungrojoo** [comment]
> csv files exported by R uses this format, right? This should be fixed with the highest priority. Thanks.
> 
> Can we change the column names in this window? if not, it is necessary also.

**Comment by seungrojoo** [comment]
@shovsj We can change the columns' names in step 3.

**Comment by seungrojoo** [comment]
I accidentally closed the issue, so opened it again.

**Comment by JaebooJung** [comment]
All of the records from the uploaded data should be treated as CSV format rather than pure strings. This feature can slow down the entire performance of uploading but I guess this is acceptable.
