### ISSUE TITLE
Transpose 속도 저하

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#537]
10만건의 데이타로 Transpose처리하면 10여분 정도 소요될 정도로
처리속도가 늦습니다.

Transpose 전 데이타 구조 (98천건) 
x1-Key x2-key  Columns value 

transpose 후 데이타 구조 (14천건)
x1-key x2-key Col_1 -- col08

소요 시간 : 10분 

데이타가 100만건인 경우, 처리가 거의 되지 않습니다. 
혹시, 개선할 수 있는 방안이 있나요?

**Comment by power4454** [comment]
넵 금방수정해서 다음 릴리즈때 내보내겠습니다.
