### ISSUE TITLE
Select Column  화면 처리 속도 저하

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#539]
500개 변수를 Select Columns 기능으로 처리하려고 하는 데
Selected Column을 누를 때마다 화면이 너무 늦게 열리고 있어요.
 처리를 다하고 화면을 닫을 때도 너무 늦어요.

화면이 멈추것처럼 보이며 최소 2분에서 3분이상 소요되는 것 같아요.

혹시, 개선 방법이 없나요?

**Comment by biue8765** [comment]
말씀하시는 기능 개선 버전은 11월 경 release 예정입니다.
