### ISSUE TITLE
python script를 이용하여 결과 그래프를 출력하는 방법

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#542]
평행축 그래프 기능이 없어서 Python Script를 이용하여 기능을 
추가하고 싶습니다. 

그런데 Script로 구현할 경우 결과 데이타만 생성할 수 있는 기능은 있네요.
하지만 그래프등의 결과 화면을 만드는 방법은 보이지 않는 데
기능이 없는지

있다면 어떻게 하면 되는 지 알려주세요.

import seaborn as sns
x = np.random.normal(size=100)
sns.distplot(x)

**Comment by power4454** [comment]
from brightics.common.repr import BrtcReprBuilder
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
x = np.random.normal(size=100)
sns.distplot(x)
rb = BrtcReprBuilder()
rb.addPlt(plt)
model=dict()
model['_repr_brtc_']=rb.get()
요렇게 하시고 output을 model로 하시면 됩니다.

**Comment by ezcyber** [comment]
output을 MODEL TYPE으로 할때 
output에 입력해야 할 변수명을 어떤것으로 주나요?
model 인가요?  model['repr_brtc']

**Comment by power4454** [comment]
넵 맞습니다.

**Comment by power4454** [comment]
_a_

**Comment by power4454** [comment]
@ezcyber 

아 repr_brtc가 아니라 언더바repr언더바brtc언더바예요. 여기서 언더바=_
뭔가 양 옆에 언더바를 붙이면 깃헙에선 제대로 입력이 안되네요.

**Comment by power4454** [comment]
@ezcyber

아 repr_brtc가 아니라 \_repr_brtc\_예요. 
뭔가 양 옆에 언더바를 붙이면 깃헙에선 제대로 입력이 안되네요. 정확히 다시 적으면
from brightics.common.repr import BrtcReprBuilder
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
x = np.random.normal(size=100)
sns.distplot(x)
rb = BrtcReprBuilder()
rb.addPlt(plt)
model=dict()
model['\_repr_brtc\_']=rb.get()

**Comment by ezcyber** [comment]
잘 처리되었습니다.
