### ISSUE TITLE
UDF 생성시 문제 및 저장된 UDF 사용 방법

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#549]
UDF를 생성하여 저장되었다고 하는 데 
메뉴에서는 보이지 않네요.

어디에서 보아야 하는지,

그리고 UDF 생성하여 저장하면 화면이 멈추고 있습니다.
저장되었다는 메시지는 나오고요.

혹시, 저만 그런가요?

**Comment by power4454** [comment]
저장한다음에 Download Json 하시고 다시 브라이틱스에서 Import UDF하시면 됩니다
