### ISSUE TITLE
Set Value를 통한 UDF 활용 방법

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#559]
앞에서 작업한 데이타 또는 변수를 받아 UDF로 활용하고자 하는 데
어떻게 해야 하나요?

Set Value로 값을 변수로  받아 UDF에서 활용하려면 어떻게 해야 하는 지 

UDF생성시 Input Configuration을 Model로 했는 데 되지 않네요

**Comment by biue8765** [comment]
1. Set Value에 변수를 생성해주시고, 뒤에 연결할 UDF의
   Input Configuration Type을 Table로 설정해주십시오.

2. Set Value에서 설정한 변수값 이름이 ${variable1} 였다면,
   UDF의 Script창에 ${variable1}로 동일하게 작성하여 사용하시면 됩니다.

**Comment by ezcyber** [comment]
아래와 같이 했는 데  UDF에서  에러나요

![image](https://user-images.githubusercontent.com/32014177/59416774-087c8300-8e01-11e9-849c-75f5b911c557.png)

![image](https://user-images.githubusercontent.com/32014177/59416724-ea168780-8e00-11e9-8553-1c3388d0267c.png)

**Comment by biue8765** [comment]
1. UDF에 Parameter가 없습니다.
   Add Parameter버튼을 클릭하시어, 파라미터를 만들어주세요(※ Control : Expression)
2. workflow상에서 생성한 UDF를 새로 import해주세요.
3. workflow상에서 UDF를 클릭하시고, 파라미터창에 ${=변수명} 입력합니다.
   (※ 변수명은 UDF앞의 Set value함수 변수명과 동일하게 입력 必)

**Comment by biue8765** [comment]
![UDF작성법](https://user-images.githubusercontent.com/44859963/59485383-9794a400-8eb0-11e9-9c0f-156b95f4d791.PNG)

**Comment by ezcyber** [comment]
해결되었습니다. 감사
