### ISSUE TITLE
Python Script를 이용한 Tensorflow 사용

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#561]
Python Script를 이용하여  Tensorflow를 사용하려고 하는 데
어떻게 Tensorflow를 설치해야 하나요?

from tensorflow.keras import layers, models
from tensorflow.keras import datasets
from tensorflow.keras import backend as K
from tensorflow.keras import optimizers

위의 코드를 이용하면  Error가 발생됩니다.

**Comment by krazyeom** [comment]
사용하고 있는 OS 가 어떤건가요?

**Comment by ezcyber** [comment]
window입니다.

**Comment by biue8765** [comment]
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
이렇게 작성해보시겠어요?

참조 : https://www.tensorflow.org/beta/guide/keras/overview?hl=ko

**Comment by ezcyber** [comment]
위의 내용으로 실행하였는 데동일하게  Error가 발생됩니다.
 
![image](https://user-images.githubusercontent.com/32014177/59483842-2e119700-8eaa-11e9-8a3e-8c23cf1b5ff1.png)

**Comment by biue8765** [comment]
tensorflow 라이브러리가 존재하지 않아 발생하는 에러 메세지로 설치 방법 가이드 드립니다.


1. 기존 Python 제거
2. Anaconda 다운로드 설치(자동으로 python(v3.7) 설치됨)
3. Anaconda에서 가상환경 생성
   1) Anaconda Prompt로 들어가서 
      >conda env list 명령어 치면 base만 존재할 것이다.
   2) 가상환경에 사용할 파이썬 버전 명시하여 설치 
      >conda create -n py36_tf14 python=3.6
      ※ 텐서플로우는 python 3.6이하에서 작동하기 때문에 Anaconda를 설치하면 python 3.7이 base에 설 
          치되지만 가상환경에서는 3.6버전으로 설치함. 
      ※ py36_tf14는 가상환경 이름으로 아무거나 써도 무방하다
   3) >conda env list 명령어 치면 이제 base,py36_tf14가 나온다.

★ 사내에서는 프록시 문제로 가상환경 생성이 되지 않는다
https://conda.io/docs/user-guide/configuration/use-winxp-with-proxy.html를 참고하여
프록시를 설정해주도록 하자. (Anaconda 설치하면 생성되는 .condarc 파일에 프록시 서버 정보를 추가해서(아래 문구 그대로 입력) 저장해야 함)

**proxy_servers:
  http: http://70.10.15.10:8080
  https: https://70.10.15.10:8080
ssl_verify: False**

   4) 생성한 가상환경을 실행한다.
      > activate  py36_tf14 (base가 py36_tf14로 변경됨)
   5)  >conda list 치면 가상환경에 python이 설치되면서 같이 설치된 library를 확인할 수 있다..

**Comment by biue8765** [comment]
pip 프록시 설정 방법

Anaconda 설치 시 pip버전이 알아서 설치되지만, conda 프록시와 마찬가지로 pip의 프록시 역시 설정해줘야한다.
A.	프록시 설정(프록시 설정에는 2가지 방식이 존재함)
①     아래의 내용을 실행하여 환경변수로 등록
> set http_proxy=http://70.10.15.10:8080
> set https_proxy=https://70.10.15.10:8080
②     pip 명령어 수행 시 파라미터로 입력
> ex) pip install –proxy 70.10.15.10:8080 (환경변수 등록 추천)

B.	SDS 인증서 설정
①     첨부된 인증서(SDS.cer) 파일을 적당한 경로에 저장
②     <User Home>에 pip 폴더 생성 후 pip.ini 파일 생성
> 보통 User Home은 C:\Users\SDS 입니다.
> 최종 경로는 C:\Users\SDS\pip\pip.ini 입니다.
③     생성한 pip.ini 파일에 아래 내용을 입력
**[global]
proxy = http://70.10.15.10:8080
cert = D:\\Private\\SDS.cer**
> cert의 경로는 다운로드한 인증서의 경로.
> 디렉토리 구분은 \\

**Comment by biue8765** [comment]
Tensorflow 를 사용하는데 필요한 라이브러리를 먼저 설치한다.

※ tensorflow설치 방법
  => pip로 설치해야 하며, 1.4버전으로 설치하도록 한다.
        (pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org tensorflow==1.4)
※ keras설치 방법
  => pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org keras

**Comment by biue8765** [comment]
[로컬_keras_install_manual.docx](https://github.com/brightics/studio/files/3289246/_keras_install_manual.docx)

**Comment by ezcyber** [comment]
tensorflow는 설치되어 있어서 아나콘다 spyder를 이용하여 사용하고 있습니다.
Brightics에서 인식할 수 있도록 해야 할 것 같은 데 
어떻게 해야 하는 지 알려주세요.

**Comment by biue8765** [comment]
@krazyeom 확인부탁드립니다.

**Comment by krazyeom** [comment]
우선 brightics-studio\lib\python\python36._pth 를 열어보면 여기 있는 경로가  PYTHONPATH 처럼 됩니다. 
Brightics Studio는 portable python을 사용해서 PYTHONPATH 환경 변수는 적용되지 않습니다. 

기본적으로 아래와 같이 구성되어 있을텐데 
```
python36.zip
.

# Uncomment to run site.main() automatically
#import site
Lib
Lib\site-packages
Scripts
C:\Users\SDS\AppData\Local\Temp\
```

아래 처럼 시스템에 구성되어 있는 anaconda의 site-packages 경로를 기입하면 PYTHONPATH 처럼  참고를 할 것입니다. 순서대로 참고 하니 적당한 위치에 옮기면 됩니다.
`D:\Users\krazyeom\Anaconda3\Lib\site-packages`

**Comment by ezcyber** [comment]
위의 내용대로 하였습니다.
Error는 나지 않는 데
아래 상태로 끝나지 않고 있네요.

 
![image](https://user-images.githubusercontent.com/32014177/59581127-daec4e00-910e-11e9-929f-96a78267450a.png)

**Comment by krazyeom** [comment]
정상적으로 PYTHONPATH가 잡히면,
brightics-studio\lib\python 로 이동해서 
`python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

결과값이 아래와 같이 나와야합니다. 
> Tensor("Sum:0", shape=(), dtype=float32)



import tensorflow as tf;
import pandas as pd
tmp = '{}'.format(tf.reduce_sum(tf.random.normal([1000, 1000])))

Result = {'Result': [tmp]}

df = pd.DataFrame(Result,columns= ['Result'])

![image](https://user-images.githubusercontent.com/442477/59647794-8e108200-91b7-11e9-97b3-05c5cf6952a8.png)


brightics-studio\lib\python\python36._pth 내용을 알려주실수 있을까요?

저는 아래와 같이 했습니다.
`C:\ProgramData\Anaconda3\envs\venv\Lib\site-packages` 부분이 가장 상단, 하단에 위치해도 동일하게 돌아갑니다. 

```
C:\ProgramData\Anaconda3\envs\venv\Lib\site-packages
python36.zip
.

# Uncomment to run site.main() automatically
#import site
Lib
Lib\site-packages
Scripts
C:\Users\SDS\AppData\Local\Temp\
```


tensorflow 의 환경은 conda env를 생성하였습니다.

**Comment by ezcyber** [comment]
위의 내용으로 Setting후 실행하였는 데
아래와 같이 Error가 발생되네요

Brightics python : error
![image](https://user-images.githubusercontent.com/32014177/59997734-b48f5b00-9698-11e9-8d6b-fe95834d47a5.png)

python : Good
![image](https://user-images.githubusercontent.com/32014177/59997759-c4a73a80-9698-11e9-984c-baa429104385.png)

**Comment by ezcyber** [comment]
Anaconda환경에서는 되지 않아  Python을 설치후
tensorflow  Ver.을 1.12.0으로 설치하여 해결하였습니다.

설비 Log에 Autoencoder를 구현

![image](https://user-images.githubusercontent.com/32014177/60004981-9d586980-96a8-11e9-85dc-66c0a9320833.png)

**Comment by admin0319** [comment]
이 문서를 참조하여 윈도우에서는 성공했습니다.
ubuntu 16.04에서는 어떻게 적용할 수 있을까요?
가이드 부탁드립니다.
감사합니다.
