### ISSUE TITLE
Hana DB Connect Error

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#564]
SAP Hana DB에서 데이타를 읽으려 하는 데 Error가 발생됩니다.

어떻게 조치해야 하나요?

Python Script하면 데이타 처리가 잘 됩니다.

![image](https://user-images.githubusercontent.com/32014177/59474130-a5cacc00-8e80-11e9-8684-59af9f43d035.png)

![image](https://user-images.githubusercontent.com/32014177/59474220-f93d1a00-8e80-11e9-9b47-672f0810960e.png)

**Comment by biue8765** [comment]
현재 사용하시는 Studio버전에서는 SAP Hana DB를 지원하고 있지 않습니다.
해당 데이터를 Studio에서 사용하시려면, SAP Hana DB에서 데이터를 내려받아 csv 형태의 파일로 만들어 load하셔야 합니다.

**Comment by krazyeom** [comment]
@biue8765 python 스크립트로 하면 잘되

**Comment by ezcyber** [comment]
python script를 이용하여 되네요.


import pyhdb
import pandas as pd
import pandas.io.sql as pd_sql
connection = pyhdb.connect(
                            host=m_host,
                            port=m_port,
                            user=m_user,
                            password=m_pwd                          )

myStatement = "SELECT * FROM tables "
df = pd.read_sql(myStatement, con=connection)
