### ISSUE TITLE
The Studio is so disorganized with no proper documentation for developers 

### ISSUE THREAD

**Issue by developeralgo8888** [brightics/studio#566]
This Brightics Studio is very disorganized . The source code and documentation is very flimsy or lacking . It's missing Deep Learning Agents including Reinforcement Learning on some of the major libraries --  Tensorflow or MXNet . Yet it does not wrap Tensorflow

**Comment by biue8765** [comment]
Thank you for your feedback. We're preparing a variety of features for your use, so please watch us with intention.
