### ISSUE TITLE
맥os 설치 문제

### ISSUE THREAD

**Issue by phg0804** [brightics/studio#567]
맥 os 사용중인 유저입니다. brightics 설치에 문제가 생겨 질문드립니다.

설치 sh파일을 실행한 뒤 생긴 brightics-studio 폴더 구성입니다.
Brightics-Studio-Launcher.exe  
start-brightics.sh
stop-brightics.sh
brightics-server/              
lib/
visual-analytics/
start-brightics.cmd

설치 가이드를 보면 아래와 같은 명령어들이 있는데,
pip -r brightics-studio\lib\requirements.txt
/brightics-studio/lib/python/python get-pip.py : This step is only needed once.
/brightics-studio/lib/python/Scripts/pip install <ANY_PACKAGES>

제 경우에는 lib폴더가 
brightics_python_env/ 
java/
etc/                  
nodejs/
이렇게 4개의 폴더로만 이루어져 위 명령어들을 실행할 수 없었습니다.
(python폴더나 requirements.txt파일이 없기 때문에)

위 명령어들을 실행하지 않은 채로 start-brightics.sh파일을 실행하고 brightics에서 load기능을 사용했을 때는
![image](https://user-images.githubusercontent.com/14102433/59825653-901d4100-936f-11e9-8290-2f8572edb4c4.png)
이와 같은 에러와 함께 실행이 되지 않았습니다.

현재 사용중인 개발환경은 다음과 같습니다.

운영체제 OS X Mojave 10.14.5
Python 3.6.5
Node js 8.11.2
JDK 1.8

어떻게 하면 해결할 수 있을까요?

감사합니다.

**Comment by biue8765** [comment]
https://github.com/brightics/studio/releases/download/v1.0-2019.05/BrighticsStudio-v1.0-2019.05-macosx.sh 로 다시 설치해보시겠어요? 
설치 가이드의 명령어는 수행하지 않으셔도 됩니다.

**Comment by phg0804** [comment]
삭제하고 첨부하여주신 파일로 재설치 해보았으나 여전히 같은 이슈가 발생합니다.
설치 과정이 sh파일 실행 한번으로 끝나는 것이 맞나요?

**Comment by biue8765** [comment]
@krazyeom 프로님 확인부탁드립니다.

**Comment by krazyeom** [comment]
github에 있는 설치 메뉴열은 빌드부터 시작해서 구성하는 방법입니다. 

별도의 java node python 이 필요 없으며, release 에서 받은 sh에 모든 필요한 패키지가 다 구성되어 있습니다. 

에러로 보아 기존에 설치된 것과 꼬여서 제대로 실행이 안되는 것 같습니다. 

stop-brightics.sh 명령어로 종료를 시킨뒤,

brightics-server/start-server.sh 파일을 수정해서 14번째 라인에 아래 스크립트를 추가 

BRIGHTICS_FUNCTION_HOME= $BRIGHTICS_SERVER_HOME/function/python
BRIGHTICS_PYTHON_PATH= $BRIGHTICS_SERVER_HOME/../lib/brightics_python_env/bin/python


이후 start-brightics.sh 로 재시작해보세요.

**Comment by phg0804** [comment]
답변 잘 확인했습니다. 다만 여전히 오류가 나서 둘째줄의 lib/brightics_python_env/bin/ 위치를 확인해봤더니 python이 존재하지 않던데 혹시 이것 때문일까요? 이 경로를 제 로컬의 python 경로로 설정하였더니 잘 작동하는 것을 확인했습니다.
우선은 이렇게 사용하면 될 것 같지만, 파이썬 실행경로만 외부에서 가져오는 게 불안정할 것 같습니다. brightics-studio 폴더 내부에 파이썬이 생성되는 위치를 알려주시면 도움이 될 것 같습니다.
감사합니다.

**Comment by krazyeom** [comment]
네, 다시 확인해보니 python 이 빠져있네요. 내부 빌드과정에서 문제가 있었는듯합니다. 월요일 오전에 다시 확인후 재 빌드해서 배포하도록 하겠습니다.

**Comment by krazyeom** [comment]
@phg0804 방금전 긴급 패치를 해서 새롭게 release에 올려두었습니다.  기존것은 삭제하시고 새롭게 받아 사용해보시길 바랍니다.

**Comment by phg0804** [comment]
@krazyeom 잘 되는 것 같습니다. 감사합니다.
