### ISSUE TITLE
Mac OS 모델 생성, 함수 이슈

### ISSUE THREAD

**Issue by phg0804** [brightics/studio#571]
안녕하세요 며칠 전 Brightics 설치 관련 문제로 질문 올렸던 sds brightics 공모전 참가자입니다. (#567 )

다름이 아니라, 새로 올려주신 패치 버전을 통해 파이썬 연동은 해결할 수 있었으나 다른 문제가 생겨 질문 올립니다. start-server.sh를 말씀하신대로 수정했음에도 불구하고, 새 모델을 만들거나 함수를 사용할 수가 없습니다.

아래는 새 모델 생성을 눌렀을 때 발생하는 오류입니다.
<img width="982" alt="Screen Shot 2019-06-25 at 12 14 44 AM" src="https://user-images.githubusercontent.com/14102433/60030709-6a30cd00-96de-11e9-90ad-8f6c8062da89.png">

아래는 기존에 만들어진 모델에 들어가서 함수 추가를 누를 때 상황입니다.
<img width="795" alt="Screen Shot 2019-06-25 at 12 15 02 AM" src="https://user-images.githubusercontent.com/14102433/60031070-0c50b500-96df-11e9-92a3-34b7d2af63c5.png">

All Functions에 들어가도 아무 함수가 없습니다. 기존에 만들어둔 Load함수는 잘 작동하는 걸로 보아 함수폴더와 연동이 제대로 안되어있는 것 같습니다.

추가적으로 , start-server.sh파일에 추가할 내용에서,
>export BRIGHTICS_PYTHON_PATH=$BRIGHTICS_SERVER_HOME/../lib/brightics_python_env/bin/python

에서 마지막 경로를 python이 아닌 python3로 해야 3.6.5와 연동되는게 아닌지 궁금합니다.

번거롭게 해드려 죄송합니다!
@krazyeom

**Comment by krazyeom** [comment]
기존 brightics-studio를 싹 다 지우시구요. BrighticsStudio-v1.0-2019.05-macosx.sh 를 실행해서 하면됩니다.

BrighticsStudio-v1.0-2019.05-macosx.sh 를 실행하면 최초 start-brightics.sh 가 실행되니 중복 실행을 할필요 없습니다.

이후 다시 시작할 때는 start-brightics.sh 하시구요. 

수정하라는 것은 지난 버전에서 안되어서 방법을 찾는거였습니다. 이번에 따로 가이드 한적이 없습니다.

**Comment by phg0804** [comment]
계속 재설치해도 안돼서 의아했었는데, 컴퓨터를 재부팅하니 정상적으로 실행됩니다.
설명 감사드립니다!!
