### ISSUE TITLE
Linux sh install error

### ISSUE THREAD

**Issue by jsh1204** [brightics/studio#573]
안녕하세요 .리눅스 버전을 설치하기위해 sh 파일을 실행시켰는데 다음과 같은 에러가 납니다. 확인 부탁드립니다.

> shyune@shyune-H370M-DS3H:~/Desktop/Studymaterial$ sh BrighticsStudio-v1.0-2019.05-linux\ \(1\).sh 
BrighticsStudio-v1.0-2019.05-linux (1).sh: 8: BrighticsStudio-v1.0-2019.05-linux (1).sh: Syntax error: "(" unexpected

**Comment by krazyeom** [comment]
chmod +x filename 으로 실행권한을 주고 한 번 실행해보시길 바랍니다. 이후 똑같은 에러가 발생하면 다시 답글 달아주세요.
