### ISSUE TITLE
Cannot execute python process. Failed to start external python process. ( 30 sec )

### ISSUE THREAD

**Issue by imhgchoi** [brightics/studio#574]
Mac OS에서 데이터 loading을 시도할 때 제목과 같은 에러가 뜹니다.
아무래도 python 경로 설정이 제대로 안됐거나 한 것 같은데 어떻게 해결해야할까요?

**Comment by krazyeom** [comment]
언제 다운로드 받으셨나요? 
문제점이 발견되어 4일전에 다시 올려두었습니다. 

https://github.com/brightics/studio/releases/download/v1.0-2019.05/BrighticsStudio-v1.0-2019.05-macosx.sh

그리고 #567 를 참고하세요. 

최초 설치시 자동으로 brightics 가 시작되니, 중복으로 start를 해줄필요가 없습니다.

**Comment by imhgchoi** [comment]
#567 에서 나와 있듯이 코드 두 줄 추가 후 재시동하여 문제가 해결되었습니다.
감사합니다.

**Comment by krazyeom** [comment]
@imhgchoi 이럴경우 추후 뭔가 library가 꼬일수 있으니 유의해주세요.
