### ISSUE TITLE
Data 저장소 위치 추가 및 명칭 수정

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#578]
Data 저장소 위치 추가 및 명칭을 수정코자 합니다.
예를 들어 상위 폴더명을 수정하거나  upload와 동일 계층에서
폴더를 생성하려면 어떻게 해야 하나요?

![image](https://user-images.githubusercontent.com/32014177/60157254-4a59f000-9829-11e9-90eb-0f17f3c6430d.png)

**Comment by krazyeom** [comment]
현재는 upload 폴더명 수정 및 폴더 생성을 지원하지 않고 있습니다.
