### ISSUE TITLE
Decision Tree화면 깨짐

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#587]
Decision Tree 결과화면에서 
Feature importance 화면이 깨져나옵니다.

이  부분이 제대로 나오게 하려면 어떻게 해야 하나요?
또는 Feature Importance로 나오는 변수의 수를 제약하려면 어떻게 해야 하나요?

![image](https://user-images.githubusercontent.com/32014177/60316836-405dfb80-99a7-11e9-942f-d554d313764c.png)

**Comment by power4454** [comment]
추후에 feature 개수에 따라 fontsize를 변하게 바꾸겠습니다.

**Comment by power4454** [comment]
임시방편으로 brightics-studio\brightics-server\functions\python\brightics\function\classification의 decision_tree_classification.py를 실행시킨 후 90번째 줄 plt.yticks(range(len(indices)), sorted_feature_cols) 요 부분에 plt.yticks(range(len(indices)), sorted_feature_cols,fontsize=5) 이런식으로 fontsize를 추가해주시면 됩니다.
