### ISSUE TITLE
Random Forest의 Feature Importance를 데이타로 받으려면

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#590]
Python Script Node을 이용하여 받을려고 하면 
어떻게 해야 하나요?

![image](https://user-images.githubusercontent.com/32014177/60328209-c6d70500-99c8-11e9-85a9-61be6366d520.png)

**Comment by power4454** [comment]
함수중에 flatten json이란 것이 있는데 이를 연결하면 feature importance를 list 형태로 받을 수 있습니다.

**Comment by ezcyber** [comment]
예제로 알려주시면 감사드립니다.

**Comment by power4454** [comment]
Decision tree classification 소세지에 flatten json를 연결한 후에 실행시키면 table의 element 중에 하나로 feature importance가 나옵니다.

**Comment by ezcyber** [comment]
연결하였는 데 두개의 변수로 나오네요.  
간단히 변수와 값을 붙여서 볼 수 있는 방법은 없을까요?
리스트도 값의 순서로 나오지 않아 두개를 매칭해야 하네요

![image](https://user-images.githubusercontent.com/32014177/60329851-2682df80-99cc-11e9-948f-f97c2db660a2.png)

**Comment by power4454** [comment]
그 이상은 현재로서는 지원하지 않는 기능이고 꼭 필요하신 기능이면 공식적으로 요청해주시면 추후 추가하겠습니다.

**Comment by ezcyber** [comment]
중요 변수를 보는 것은 매우 중요합니다.  이 부분의 기능이 반영되었으면 합니다.

**Comment by ezcyber** [comment]
Importance값을 Table로 받고자 합니다.
어디를 수정하면 될까요

**Comment by power4454** [comment]
제일 간편한건 flatten json에 python script를 연결해서 다음과 같이 입력하면 됩니다. 순서가 중요하시면 sort를 하시면 됩니다.
import pandas as pd
feature_cols = inputs[0].feature_cols[0]
feature_importance = inputs[0].feature_importance[0]
result = pd.DataFrame([[feature_cols[i],feature_importance[i]] for i in range(len(feature_cols))],columns = ['feature_name','importance'])

![image](https://user-images.githubusercontent.com/45587294/61684192-8a8e8e80-ad53-11e9-9b30-393e5bad76ac.png)

**Comment by power4454** [comment]
급하게 필요하신거면 brightics-studio\brightics-server\functions\python\brightics\function\classification에 random_forest_classification.py의 _random_forest_classification_train 정의부 맨 밑에 다음 구문을 추가히사고 Get Table 함수로 feature_importance_table를 불러오시면 됩니다.

model['_repr_brtc_'] = rb.get()
    feature_importance = classifier.feature_importances_
    feature_importance_table = pd.DataFrame([[feature_cols[i],feature_importance[i]] for i in range(len(feature_cols))],columns = ['feature_name','importance'])
    model['feature_importance_table'] = feature_importance_table
    return {'model' : model}

**Comment by ezcyber** [comment]
위의 내용대로 했는 데 결과가 나오지 않아요

![image](https://user-images.githubusercontent.com/32014177/61723679-81c7a800-ada7-11e9-9f67-fcffcd781b77.png)


![image](https://user-images.githubusercontent.com/32014177/61723797-ae7bbf80-ada7-11e9-95e0-bdab9d44a9b6.png)

**Comment by power4454** [comment]
넵 그 상태에서 Get Table이란 이름의 소세지(함수)를 연결시켜서 키값에 feature_importance_table를 입력하시면 됩니다.

**Comment by ezcyber** [comment]
Get table로 연결을 시키라고 했는 데 잘 이해가 되지 않아요. 
Sample 프로그램이나 화면을 보여주시면 이해가 편할 것 같아요

**Comment by power4454** [comment]
![image](https://user-images.githubusercontent.com/45587294/61769206-6fd81a80-ae24-11e9-858c-7725b6a15c6d.png)

**Comment by power4454** [comment]
이렇게 하시면 됩니다.

**Comment by ezcyber** [comment]
잘 동작합니다.

Decision Tree의 Feature Importance도 위의 코드를 그대로 사용해도 될까요?

**Comment by power4454** [comment]
네 똑같이 쓰시면 됩니다
