### ISSUE TITLE
[Statistic Summary-Input Columns-Select All] button doesn't work.

### ISSUE THREAD

**Issue by hj-yun** [brightics/studio#592]
[Select All] button from [Statistic Summary-Input Columns] doesn't work.

**Comment by power4454** [comment]
We cannot reproduce what you mentioned. Can you give me model json file(see below image) and input data file?
![image](https://user-images.githubusercontent.com/45587294/60586697-8c58d800-9dcd-11e9-9c69-0b84aa6c00de.png)

**Comment by hj-yun** [comment]
I made a simple model, '[Load]->[Statistic Summary]'.
As you can see below, [Select All] button didn't work properly.

![issue](https://user-images.githubusercontent.com/34854423/60646044-46574f00-9e75-11e9-9da9-cb420a231fea.png)

I'm currently using brightics-studio-ver(2019-06) in Ubuntu(16.04.6 LTS).
I fixed this problem by updating software of Ubuntu.
Thanks for help.
