### ISSUE TITLE
파일 에러입니다.

### ISSUE THREAD

**Issue by ottogiba** [brightics/studio#593]
파일 읽어오는 과정에서 에러가 발생합니다.

Python script error : pandas.errors.ParserError: Expected 1 fields in line 946, saw 2
( 2 sec )

**Comment by krazyeom** [comment]
어떤 파일이 문제인지 확인하기 위해 첨부파일로 올려주실수 있나요? 
만약 퍼블릭으로 공개되지 않아야하는 데이터이면, sungwook.yeom@samsung.com 주시면 확인후 패기 하겠스비낟.
