### ISSUE TITLE
Feature selection  기능이 있나요

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#595]
많은 변수가 있는 경우, Feature Selection을 먼저 해야 하는 데
Feature Selection의 기능이 있는지 요청드립니다.

**Comment by power4454** [comment]
현재 Brightics Enterprise(유료버전)에는 feature engineering을 위한 각종 auto함수들(auto feature selection 포함)이 있지만 studio버전에서는 탑재되어있지 않습니다. 다만, 추후 개발계획은 잡혀있는 상태로 기다려 주시면 감사하겠습니다.
