### ISSUE TITLE
filter 기능에서 in 에 넣어야 하는 형식

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#597]
Filter기능에서 in으로 여러값을 넣고 싶은 데 
어떤 형식으로 넣어야 하나요?

![image](https://user-images.githubusercontent.com/32014177/60939376-5908d280-a312-11e9-8a5a-8e82fcd473d5.png)

**Comment by biue8765** [comment]
['setosa','virginica'] 이런 형식으로 작성해주시면 됩니다 ^^

**Comment by ezcyber** [comment]
감사합니다.
