### ISSUE TITLE
Studio 사용 인증창 지원 문의

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#599]
제가 설치한 Studio를 특정 사람에게만 Open하려고 하는 데
이 경우 기능이 지원하나요?

**Comment by krazyeom** [comment]
로그인 기능이 제공되지 않아서 지금 사용하고 있는 포트를 3000에서 다른 포트로 변경을 하고 특정 사람에게 전달하면 어떨가 싶습니다.

**Comment by ezcyber** [comment]
자세히 설명을 요청드립니다.
 포트별로 사용자 제약을 하라는 의미인지......

**Comment by krazyeom** [comment]
Brightics Studio 1인 기준으로만 사용하게 설계가 되어서 사용 인증창은 따로 제공하지 않고 있습니다. 

Linux 에 설치해서 사용한다면  host deny 기능을 이용해서 특정 IP만 필터를 걸어도 될것 같습니다. 


윈도우에서 공유를 한다면, port를 3000 대신 5000 등으로 변경을 하고 공유하고 싶은 사람에게 알려주면 될것 같은데요?

**Comment by ezcyber** [comment]
혹시, 인증 관리할
