### ISSUE TITLE
filter에서 AND와 OR를 동시에 사용

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#600]
and 와 or를 동시에 사용하려고 하는 데
기능이 있는지 확인이 되지 않네요.

어떻게 해야 하나요?

![image](https://user-images.githubusercontent.com/32014177/61179649-fc732380-a641-11e9-96da-d80f36b1e0e1.png)

**Comment by krazyeom** [comment]
filter 함수가 아니라 query 인가요? 전체 내용 텍스트를 붙여넣기 하실수 있나요?

**Comment by ezcyber** [comment]
Filter 기능에서 입니다.
![image](https://user-images.githubusercontent.com/32014177/61184806-d626a580-a68c-11e9-8196-9507edc142a0.png)

**Comment by krazyeom** [comment]
동시에 사용은 안됩니다.

**Comment by ezcyber** [comment]
Coding 창을 주면 좋을 것 같습니다.
