### ISSUE TITLE
Multi Chart Option이 보이지 않는 현상

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#601]
Multi Chart에서 옆에 option창이 보이다가 보이지 않다가 해요.

데이타에 따라 그런가요?

![image](https://user-images.githubusercontent.com/32014177/61184791-a7103400-a68c-11e9-98df-0ea787c82be2.png)
![image](https://user-images.githubusercontent.com/32014177/61184791-a7103400-a68c-11e9-98df-0ea787c82be2.png)

**Comment by ezcyber** [comment]
OPTION이 보이는 경우

![image](https://user-images.githubusercontent.com/32014177/61192661-09028500-a6f1-11e9-869f-4fd864892015.png)

**Comment by iisejin** [comment]
혹시 다음의 두 가지 경우에 해당하나요?

1. Model에 Python Script가 존재할 경우
2. GroupBy에서 컬럼타입이 Integer/Long 일 경우

현재 두 가지 상황에서  오류가 발생하는 것으로 파악되어 패치 예정입니다.

**Comment by ezcyber** [comment]
저의 경우는 컬럼 타입이 long인 경우인것 같네요.
컬럼 타입을 다른 것으로 바꿀려면 어떻게 해야 하나요?

**Comment by krazyeom** [comment]
![image](https://user-images.githubusercontent.com/442477/61196362-25aab700-a709-11e9-95c7-d7c1af3f5fca.png)

Select Column 이란 함수를 사용하면 다른 타입으로 변경가능합니다.

**Comment by ezcyber** [comment]
감사합니다.
