### ISSUE TITLE
transpose 속도 저하

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#602]
최근 Ver에서 Transpose 성능이 개선되었다고 되어 있네요.
하지만 아직도 성능이 만족되지 않네요.

FDC와 같은 데이타를 사용하여 Transpose 작업이 필수적인데
 초당 데이타에 1000개의 Tag이상 처리해야 하는 데 시간이 너무 소요됩니다.

3분이내로 작업하는 경우, 어느 정도의 데이타(Tag수, Row수)등으로 해야 하는 지 
추천을 해주셨으면 합니다.

아래는 지난 번 성능이 나오지 않아 요청한 내용입니다.
10만건의 데이타로 Transpose처리하면 10여분 정도 소요될 정도로
처리속도가 늦습니다.

Transpose 전 데이타 구조 (98천건)
x1-Key x2-key Columns value

transpose 후 데이타 구조 (14천건)
x1-key x2-key Col_1 -- col08

소요 시간 : 10분

데이타가 100만건인 경우, 처리가 거의 되지 않습니다.
혹시, 개선할 수 있는 방안이 있나요?

**Comment by krazyeom** [comment]
네, 원인을 찾았으며 곧 반영이 될 예정입니다.  반영 이후 소스 부분을 알려드리면 직접 수정하시면 패치 때까지 기다리지 않으셔도 될 것 같아요.

**Comment by ezcyber** [comment]
감사합니다.

**Comment by ezcyber** [comment]
현재 상태에서 속도가 너무 느려 작업이 어렵네요.  수정할 소스 부분을 알려주시길 바랍니다.

**Comment by power4454** [comment]
D:\brightics-studio\brightics-server\functions\python\brightics\function\transform의
reshaping.py 에서 _transpose 부분을 다음과 같이 통째로 바꿔주시면 됩니다.



def _transpose(table, input_cols, label_col=None, label_col_name='label'):
    feature_col_name = [col for col in table.columns if col in input_cols]
    sort_table = table[feature_col_name]
    
    out_table = sort_table.transpose()
    len_table = len(table)
    
    if label_col is None:
        out_table.columns = ['x'+str(i+1) for i in range(len_table)]
    else:
        out_table.columns = [str(table[label_col][i]) for i in range(len_table)]
    
    out_table.insert(loc=0, column=label_col_name, value=feature_col_name)

    return{'out_table':out_table}

**Comment by power4454** [comment]
def _transpose(table, input_cols, label_col=None, label_col_name='label'):

    sort_table = pd.DataFrame()
    feature_col_name = [col for col in table.columns if col in input_cols]
    sort_table = table[feature_col_name]
    out_table = sort_table.transpose()
    len_table = len(table)
    
    if label_col is None:
        out_table.columns = ['x'+str(i+1) for i in range(len_table)]
    else:
        out_table.columns = [str(table[label_col][i]) for i in range(len_table)]
    
    out_table.insert(loc=0, column=label_col_name, value=feature_col_name)

    return{'out_table':out_table}

**Comment by power4454** [comment]
def _transpose(table, input_cols, label_col=None, label_col_name='label'):
    feature_col_name = [col for col in table.columns if col in input_cols]
    sort_table = table[feature_col_name]
    out_table = sort_table.transpose()
    len_table = len(table)
    if label_col is None:
        out_table.columns = ['x'+str(i+1) for i in range(len_table)]
    else:
        out_table.columns = [str(table[label_col][i]) for i in range(len_table)]
    out_table.insert(loc=0, column=label_col_name, value=feature_col_name)
    return{'out_table':out_table}

**Comment by ezcyber** [comment]
위 코드를 적용하면 다른 함수에서 Error가 발생합니다.

**Comment by power4454** [comment]
들여쓰기를 안 하신거 아닐까요? 
원래 함수 def 후에 space를 4번씩 눌러야 하는데 위에 코드 그대로 복사하면 맨 앞에 스페이스 부분이 없어지네요

**Comment by power4454** [comment]
inconsistent use of~ 에러의 경우 tab이랑 스페이스 4칸 등을 혼용해서 쓸 경우 나는 에러입니다. 쥬피터 노트북이나 기타 파이썬 프로그램은 알아서 tab을 스페이스 4칸으로 치환해주는데 메모장 같은 애들은 그렇지 않거든요. 혹시 tab으로 들여쓰기를 하셨다면 전부 스페이스 4칸으로 바꿔주세요.

**Comment by ezcyber** [comment]
어제는 3분에서 40초내외로 개선이 되었네요.

![image](https://user-images.githubusercontent.com/32014177/61845638-1c76d280-aedf-11e9-861e-b925233403f2.png)

데이타가 3,800건이고 transpose되는 변수가 2개인데 그래도 속도 개선이 필요하네요

100만건을 돌리려고 해도 엄두가 나지 않고 서버 전체의 자원을 먹고 있어서 다른 작업이 안되네요.

**Comment by power4454** [comment]
![image](https://user-images.githubusercontent.com/45587294/61846459-2948f580-aee2-11e9-86f3-e12f319937fd.png)

![image](https://user-images.githubusercontent.com/45587294/61846483-37971180-aee2-11e9-925e-f13d8aa8afba.png)

**Comment by power4454** [comment]
자체 테스트 결과 10만 row 100개 column에서 같은 코드로 brightics는 13초, 쥬피터 노트북은 58.2ms로 확인되었습니다.
원인은 아마도 brightics의 경우 table을 display할 때 10만개의 데이터를 전부 display하느라 느린 것으로 판단되며 VA팀과 상의하여 고치도록 하겠습니다. 감사합니다.

**Comment by ezcyber** [comment]
Pivot으로  220만건의 경우  5분정도로 처리하였습니다.
 Transpose로는 처리 불가...

![image](https://user-images.githubusercontent.com/32014177/62346183-224c6380-b530-11e9-85b7-8df21b9c2da4.png)
