### ISSUE TITLE
데이타를 download하면 한글이 깨져요

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#603]
파일로 받으면 한글이 깨져요.

어떻게 조치해야 하나요?

![image](https://user-images.githubusercontent.com/32014177/61273077-a50cb900-a7e3-11e9-9335-4e09d6ad19a1.png)

![image](https://user-images.githubusercontent.com/32014177/61273052-8f978f00-a7e3-11e9-8714-278b80b0e2bf.png)

**Comment by krazyeom** [comment]
원인을 파악하여 내부에서 수정중입니다. 월말에 릴리스 되는 버전에 추가 될 예정입니다.

**Comment by krazyeom** [comment]
#609 에 해결되었으며, 테스트 해보니 잘 됩니다. 다음버전에 포함될 예정입니다. 

![image](https://user-images.githubusercontent.com/442477/61608517-f5759200-ac8d-11e9-99e3-2106625a86cd.png)
![image](https://user-images.githubusercontent.com/442477/61608529-fe666380-ac8d-11e9-862e-89caf619af2e.png)

급하게 필요하신 사항이면  `va-server/visual-analytics/routes/api/va/v2/data.js`  파일을 열고 

`res.write(Buffer.from('EFBBBF', 'hex'));` 구문을 아래와 같이 추가하면 됩니다. 

```
    __BRTC_CORE_SERVER.setBearerToken(options, req.accessToken);
    res.write(Buffer.from('EFBBBF', 'hex'));
    request(options).pipe(res);	    request(options).pipe(res);
```

**Comment by ezcyber** [comment]
위의 코드 수정으로 처리가 되었습니다
