### ISSUE TITLE
Summary 속도 저하

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#605]
130만건 정도의 데이타를 Summary하는 데
3분이상 소요되고 있어요.

Group에는 일자 및  Tag일데 
일자는 20일, Tag는 60개 정도입니다. 

통계치는 평균, 표준표차, 갯수

일반 DB에서는 10초 이내에 나오는 데 너무 오래 걸리네요 

다른 방법이 없을까요

**Comment by krazyeom** [comment]
데이터 130만건, 컬럼 30개, 그룹 1300개로 해서 내부 테스트 해보니 10여초 걸리고 있습니다.

4월 버전 기준으로 패치가 되었습니다. 혹시 언제 버전을 사용하고 계신가요?

**Comment by power4454** [comment]
좀 더 빠르게 만들 수 있긴한데 만드는데 시간이 좀 걸려서 보류해뒀던 사항입니다. statistic summary는 자주 사용하는 함수일테니 바꿔서 다음버전에 올리겠습니다.

**Comment by power4454** [comment]
혹시 parameter에 workers를 넣으셨나요? 이건 원본데이터가 너무 클 경우 오히려 느려지는 현상이 있어서 수정하려고 하고있어요.

**Comment by power4454** [comment]
혹시 workers parameter에 값을 넣으셨나요? 이건 data에 비해 연산이 적은 경우엔 속도가 오히려 느려지는 현상이 있어서 수정하려고 보고있는중이에요. 혹시 사용하셨다면 없애고 테스트해주세요.

**Comment by ezcyber** [comment]
workers parameter 넣는 곳을 알지 못합니다.  현재는 Default로 되어 있습니다

**Comment by ezcyber** [comment]
workers parameter는 어디에서 보나요?

**Comment by power4454** [comment]
![image](https://user-images.githubusercontent.com/45587294/61925295-a2aa1c00-afa6-11e9-8d37-5f8722a18b84.png)
여기 맨 밑에 있습니다.
