### ISSUE TITLE
 Workflow 부분 복사 또는 제거 기능

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#606]
Workflow를 작성하다 보니 너무 많아 
부분 복사하여 다른 WorkFlow에 넣거나 쓸데없는 노드를 한번에 
제거하고 싶은 데 어떤 방법이 있나요?

![image](https://user-images.githubusercontent.com/32014177/61498862-f98c8000-a9ff-11e9-9884-525e241d5ba9.png)

**Comment by krazyeom** [comment]
![image](https://user-images.githubusercontent.com/442477/61512300-69b4f900-aa34-11e9-9337-9e54b40253a3.png)
제거의 경우는 드레그로 영역을 선택후 X 아이콘을 누르면 삭제 됩니다.

**Comment by krazyeom** [comment]
위 그림에서 가장 오른쪽 아이콘 Copy to Clipboard 를 사용하면 클립보드로 복사가 됩니다. 세션이 유지될때만 사용가능합니다. 저장기능은 없습니다.  그리고 아래 그림 처럼 아이콘을 클릭하면 클립보드에 복사된 함수들이 나오고 그걸 다른 모델에서 사용하면 됩니다. 
![image](https://user-images.githubusercontent.com/442477/61512499-20b17480-aa35-11e9-8452-de0203c57fb3.png)

**Comment by krazyeom** [comment]
또는 위 그림에서 X 옆 2번째 Add to Template 를 클릭하면 저장이 됩니다. 그리고 사용방법은 오른쪽 팔레트에서 Template에서 보이게 되며, 이를 사용하면 됩니다. 
![image](https://user-images.githubusercontent.com/442477/61512660-9b7a8f80-aa35-11e9-9e8c-c3bd6cf363be.png)

**Comment by ezcyber** [comment]
잘 동작이 되네요.  좋은 기능이네요. 감사
