### ISSUE TITLE
문자열 Concat

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#607]
2개 Column을 Concat하려고 하는 데
1개는 문자값을 갖고 있고 1개의 Column은 null로 되어 있어요.

두개를 아래 방식으로 Concat하면 Null이 나오는 데
어떻게 하면 될 까요?

 
![image](https://user-images.githubusercontent.com/32014177/61508629-a9c0af80-aa25-11e9-9215-b8d99392e02d.png)

**Comment by krazyeom** [comment]
"TEST", null 을 concat을 하면 "TEST"만 이렇게 나오길 원하시는건가요?

**Comment by krazyeom** [comment]
sqlite 문법인 COALESCE 함수를 써서 null을 '' 빈값으로 변환해서 concat 하면 그림과 같이 결과가 나옵니다.

![image](https://user-images.githubusercontent.com/442477/61599235-e973db00-ac61-11e9-8e58-b648f5669429.png)

**Comment by ezcyber** [comment]
Null일 경우도 있어 이 부분도 함수 사용없이 그냥 사용하면 좋을 것 같습니다.
