### ISSUE TITLE
Read CSV 처리시 한글 처리 오류

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#610]
6월달 Ver.으로 Upgrade했는 데 기존에 잘 처리되던 CSV 
csv import 할때 UniDecoding ERROR 가 나고 있어요. 
어떤 부분을 수정해야 하나요?

6월 Ver.
![image](https://user-images.githubusercontent.com/32014177/61615596-5bb7e000-aca1-11e9-9594-277e34d2a26c.png)

이전 Ver.

![image](https://user-images.githubusercontent.com/32014177/61615697-a6d1f300-aca1-11e9-8ada-16ecf8a0934c.png)

**Comment by power4454** [comment]
갖고계신 csv 파일의 encoding 방식에 따라 대처 방법이 다릅니다. https://rfriend.tistory.com/250 여기에 5번을 보시면 코덱을 확인해봐야 할 것 같습니다. 
그런데 이전 버전에서는 제대로 됐는데 갑자기 안된다면 #479 가 조금 의심스럽긴한데, 이는 원래 한글의 경우 "utf-8"를 많이 사용해서 굳이 encoding 방식을 "utf-8"로 바꿔준건데, 이게 오히려 "utf-8"방식을 사용하지 않는 csv파일에 대해서는 오류를 발생시킬수도 있을 것 같습니다.

**Comment by power4454** [comment]
혹시 brightics-studio\brightics-server\functions\python\brightics\common\data 폴더의 table_data_reader.py의

def read_csv(path):
    return pd.read_csv(path, engine='python', quoting=3, encoding='utf-8', na_filter = False)

여기에서 encoding='utf-8' 부분을 지우고 

def read_csv(path):
    return pd.read_csv(path, engine='python', quoting=3, na_filter = False)

이렇게 바꾼 뒤에 돌려보실 수 있을까요?

**Comment by power4454** [comment]
power4454@snu.ac.kr 이나 oper.kang@samsung.com으로 데이터 보내주시면 확인해보겠습니다.

**Comment by ezcyber** [comment]
encoding 부분을 삭제해서 해결이 되었습니다.

csv가 utf-8도 사용할 수 있어 Option을 추가하여 utf-8 또는 다른 형태도 사용할 수 있으면 좋을 것 같습니다.

**Comment by krazyeom** [comment]
@ezcyber 지금 다른곳에서도 encoding 으로 인한 비슷한 이슈가 있어, UDF (User Define Function)을 제작하여 따로 배포하고 있습니다. 

https://gist.github.com/krazyeom/67747f83e725d42c3a54a5a7a97b4248 가서 json 파일을 받으시구요. 

오른쪽 팔레트를 클릭하고 아래 Import UDF를 선택하고 파일을 로드하시면,
![image](https://user-images.githubusercontent.com/442477/61672202-b2ff9400-ad25-11e9-9a90-2f64daf63c77.png)

UDF가 등록되고 이걸 사용하시면 됩니다. 
![image](https://user-images.githubusercontent.com/442477/61672240-da566100-ad25-11e9-9a7c-805aff611537.png)
