### ISSUE TITLE
Read_CSV기능 숫자 필드 변환 문제

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#611]
read_csv에서 숫자값이 있어 숫자필드로 인식하였는데
19년 6월 Ver.으로 변경하고 나서는 숫자로 인식하지 않고 문자로 인식합니다.

![image](https://user-images.githubusercontent.com/32014177/61676556-6e7cf400-ad37-11e9-9a69-3ba8bc88ccae.png)

해당 데이타를 python으로 하면 숫자로 인식합니다
![image](https://user-images.githubusercontent.com/32014177/61676658-c7e52300-ad37-11e9-8e93-c9b1372e13bb.png)

**Comment by ezcyber** [comment]
어디를 수정해야 할까요?

**Comment by power4454** [comment]
확인 결과 na_filter를 false로 바꾸면서 생긴 side effect로 확인되었습니다. 데이터 중간에 null이라든지 빈칸이 있으면 read_csv가 이를 string ' ' 등으로 인식해버리면서 전체 column을 전부 string으로 변환시켜 버리네요. 해결방법은 2가지가 있습니다.
1. select column을 통해 강제로 type 변환.
2. brightics-studio\brightics-server\functions\python\brightics\common\data 폴더의 table_data_reader.py의

def read_csv(path):
return pd.read_csv(path, engine='python', quoting=3, encoding='utf-8', na_filter = False)

여기에서 na_filter = False 부분도 지우고

def read_csv(path):
return pd.read_csv(path, engine='python', quoting=3)

이렇게 바꾼 뒤에 돌리면 돌아갈것입니다.

**Comment by power4454** [comment]
추후에 na_filter와 encoding 둘 다 수정해서 배포하겠습니다.

**Comment by ezcyber** [comment]
1번 사항으로 해 봐는 데 String으로 되어 있어서 Select Column에서 Error가 나네요.
2번으로 해결해야 할 것 같아요.

**Comment by ezcyber** [comment]
2번사항으로 해결이 되었습니다. 
그런데 delete등  다른 기능에서 처리Error가 나요.

![image](https://user-images.githubusercontent.com/32014177/61839608-35748900-aec9-11e9-8515-7f566047b680.png)


![image](https://user-images.githubusercontent.com/32014177/61839636-491fef80-aec9-11e9-98fd-2f42737d5ce0.png)

**Comment by ezcyber** [comment]
위 내용은 다른 코드 수정으로 발생된 내용이네요
