### ISSUE TITLE
Load에서 Data Add시 한글인식 문제

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#612]
Excel에서 한글값이 Load의 Data Add화면에서 깨져서 인식못하고 있어요
Add data 
![image](https://user-images.githubusercontent.com/32014177/61677399-738f7280-ad3a-11e9-8790-5b1709523197.png)

excel
![image](https://user-images.githubusercontent.com/32014177/61677427-8dc95080-ad3a-11e9-8353-2b261866e959.png)

**Comment by krazyeom** [comment]
#610 파일 제일하단에 read csv with encoding 이라는 ufd를 만들어 드렸습니다. 
이걸로 되는지 한 번 확인 부탁드립니다. 

이 함수는 preview가 없이 선택한 encoding 으로 바로 load를 하게 됩니다.
