### ISSUE TITLE
workflow내의 Function 숫자 제약 

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#613]
60개이상의 함수노드를 이용하려는데 더 이상 사용할 수 없다는 
Warning이 나옵니다.

제약을 풀 수 있나요?

어떻게 해야 하나요?

**Comment by krazyeom** [comment]
오픈소스 버전의 Studio는 Function을 60개로 제한하고 있습니다. 사용버전의 Ent/Std 버전은 제한이 없습니다. 

다만, Sub Flow라는 기능을 제공하여 만든 모델을 연결하여 사용하면 60개 제한을 피해서 사용할 수 있습니다. 

http://URL:PORT/api/va/v2/help/function/Flow?type=data&context=common 
으로 전근하면 메뉴얼이 제공되고 있습니다. 

사용해보시고 문의사항 있으면 남겨주세요.

**Comment by ezcyber** [comment]
메뉴얼이 접근되지 않네요.

**Comment by krazyeom** [comment]
URL:PORT 부분을 변경해서 접근하신게 맞나요?

/api/va/v2/help/function/Flow?type=data&context=common

끝에 붙여 넣어서 접근 확인 부탁드립니다.

**Comment by ezcyber** [comment]
매뉴얼에서는  Flow에서 Return으로 정의한 데이타가 Flow 정보로 나오는 데 
실제로는 나오지 않네요.
Bug인가요?

매유얼 
![image](https://user-images.githubusercontent.com/32014177/62185198-6eff3580-b39c-11e9-9a82-f4249bbed625.png)


Flow 정의 내용시 Returned Data 지정
![image](https://user-images.githubusercontent.com/32014177/62185222-8d653100-b39c-11e9-9c96-6195b82cd155.png)

Flow 정보 확인하면 Input  / Return Table이 보이지 않네요

![image](https://user-images.githubusercontent.com/32014177/62185347-01073e00-b39d-11e9-8aa7-fd61511e58fe.png)
