### ISSUE TITLE
UDF 생성시 앞의 Table을 받을때 방법

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#616]
UDF를 이용하여 앞의 데이타를 받고 싶은데 UDF에서는 어떻게 해야 하나요.

![image](https://user-images.githubusercontent.com/32014177/61916929-9f526880-af85-11e9-8d44-6eb5e0ae1093.png)

![image](https://user-images.githubusercontent.com/32014177/61916905-80ec6d00-af85-11e9-8b6a-73b2bb8bd302.png)

**Comment by krazyeom** [comment]
보내주신 예제에서는 df[0] 으로 하면 입력이 받아질겁니다. 
예) df1=df[0]

![image](https://user-images.githubusercontent.com/442477/61917264-310ea580-af87-11e9-9985-13f51a955004.png)

![image](https://user-images.githubusercontent.com/442477/61917344-99f61d80-af87-11e9-9709-b85535401084.png)

**Comment by ezcyber** [comment]
해결이 되었습니다. 감사
