### ISSUE TITLE
Multi chart를 Function으로 처리할 수 있는 방안

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#617]
Multi-Chart기능이 좋아서 많이 활용하고 있습니다.
그런데 선택하는 내용이 고정적이지 않아 항상 새로게 지정하여
설명하고 하고 있는 데  Function기능을 이용하여 사용할 변수를 
미리 Setting하는 방안이 있으면 좋을 것 같습니다.

현재는 20개의 시나리오에 따라 Multi-Chart가 같은 데  매번 지정하고 있어서 
매우 번거롭습니다.

해결방안이 있을까요 

![image](https://user-images.githubusercontent.com/32014177/61917412-0709b300-af88-11e9-925b-b3518ad9c1ba.png)

**Comment by biue8765** [comment]
문의해주신 게 함수별로 사용하는 multi chart타입 세팅 파라미터가 동일한데 매번 동일한 내용을 세팅해야 되냐는 내용이 맞으신가요?

위의 내용이라면, 현재로써는 함수별로 현재처럼 차트 세팅 내용이 동일하더라도 여러번 작업해주셔야 하는 방법밖에는 없습니다.  보내주신 내용 관련하여 개선방안 및 구체적인 계획이 수립되면 해당 이슈에 코멘트로 공유드리겠습니다.
