### ISSUE TITLE
MemoryError issue

### ISSUE THREAD

**Issue by admin0319** [brightics/studio#619]
안녕하세요.
첨부와 같이 2천건의 데이터를 Association Rule에 Run 하면 MemoryError가 발생하면서 멈춥니다.
스튜디오 서버 메모리 설정을 늘리고 싶은데 어떤 설정을 수정하면 될까요?

(브라이틱스 스튜디오가 설치된 장비의 메모리는 128g로 여유가 있습니다.)

[오류 Log.txt](https://github.com/brightics/studio/files/3434131/Log.txt)

![이미지 33](https://user-images.githubusercontent.com/35323888/61925401-18ae8300-afa7-11e9-93b0-aeff6c46a929.png)

**Comment by power4454** [comment]
Association rule의 경우 Min Support를 엄청 작게 설정하면 O(2^n)까지 도는 무거운 작업인데 혹시 Min Support를 조금 높게 바꿔보시는건 어떨까요? 

메모리 설정에 대한 내용은 다른분이 답변해주실 거예요.

**Comment by krazyeom** [comment]
메모리 설정은 기본적으로 limit 걸어놓은것이 없습니다. 첨부 그림으로 봐서는 36분 51초 돌았다는 것은  그 이후에 128기가를 다 쓰다가 Memory Error가 난것으로 보입니다. 

위 답변처럼 Min Support를 변경해서 모델링을 다시해보시는것을 권장드립니다.

**Comment by admin0319** [comment]
Min Support 조정으로 답을 찾았습니다. 
빠른 답변 감사합니다. ^^
