### ISSUE TITLE
Process Pending 처리 방안

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#620]
WorkFlow와 Multi Graph를 동시에 작업하면
한쪽 작업이 되지 않거나 어떤 경우는 Multi Graph 작업에서 Error가 발생됩니다.

시스템 Monitoring을 보면 자원은 충분한 데
해결 방안이 있을까요?

브라우져 2개로 작업해도 동일 현상이 나타나네요.

![image](https://user-images.githubusercontent.com/32014177/62007179-6aacff80-b185-11e9-9bcb-c50becb78f3e.png)

![image](https://user-images.githubusercontent.com/32014177/62007193-82848380-b185-11e9-9057-bd7f3d28961d.png)

![image](https://user-images.githubusercontent.com/32014177/62007205-9fb95200-b185-11e9-8a46-adc105a9b853.png)

**Comment by krazyeom** [comment]
Brightics Studio는 Single 유저만 지원가능합니다. 

모든 작업은 유저당 순차적으로 Queue에 넣어서 처리됩니다.  브라우져 2개나 동시에 작업을 처리하려면 큐에 쌓여 있어 Process Pending 상태로 됩니다.

**Comment by ezcyber** [comment]
상용 Ver.도 동일한 가요?

**Comment by krazyeom** [comment]
사용버전은 다 유저 지원 및 동시 job 처리 등 다양한 기능을 지원합니다.
