### ISSUE TITLE
Pop Up Chart 데이타 건수 제약 해소 방안

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#621]
그래프를 그리고자 하는 데이타량이 30만건이 되는 데 
Pop-Up Chart에서 Filter를 이용하여 여러가지 그래프를 작업하려고 하는데
그려지는 데이타량이 제약되네요.

혹시, 해결 방안이 없을 까요?
매번마다 Filter를 걸어서 데이타를 줄이고 하는 작업이 너무 
어렵네됴.

**Comment by iisejin** [comment]
URL에 limitArr값을 변경하면 최대 조회 가능 데이터 사이즈가 변경됩니다. ex) limitArr=50000
다만 Pop-Up Chart에서는 50,000건 이상의 데이터 조회 시 상황에 따라 Browser가 다운될 수 있습니다.

**Comment by ezcyber** [comment]
더 많은 데이타를 출력하려면 어떻게 해야 하나요?
5만건이상의 그래프 출력은 Brightics에서는 지원하지 않나요?
