### ISSUE TITLE
Word2Vec 평균값 문의

### ISSUE THREAD

**Issue by admin0319** [brightics/studio#622]
안녕하세요.

여러 문장들을 Word2Vec 를 통해 단어 벡터를 만들었습니다.
예시를 위해 벡터는 2차원으로 하였고 첫번째 이미지의 빨간색 네모의 '수수료' 란 단어의 벡터는 
[0.14801540970802307,-0.9889850616455078]
로 생성되었습니다.
![이미지 1](https://user-images.githubusercontent.com/35323888/62175725-9ee91180-b379-11e9-8299-e9b702b38d93.png)

이 Word2Vec 모델을 가지고 문장의 벡터를 구하기 위해 Word2Vec Model을 Run 하게 되면 다음과 같이 값이 바뀌는데 왜 그런가요?
![이미지 2](https://user-images.githubusercontent.com/35323888/62175848-0b641080-b37a-11e9-9f04-6ca448f63699.png)

문장내 단어가 여러개 있으면 평균값을 쓴다고 했는데 단어가 하나일때도 값이 다른 이유와

다음과 같이 문장내 단어가 여러개일때 계산한 평균값과 Word2Vec Model 의 평균값이 다른 이유도 알고 싶습니다.

![image](https://user-images.githubusercontent.com/35323888/62175923-5da53180-b37a-11e9-9bfa-32ded4f6d3ba.png)

확인 부탁드립니다.
감사합니다.

**Comment by biue8765** [comment]
@hyoxt121 프로님, 최지은 프로님으로 본 이슈 할당부탁드립니다.

**Comment by jen-choi** [comment]
안녕하세요. 말씀해주신 내용 확인해보니 word와 word vector 간 매칭 문제가 있는 것으로 파악되었습니다. 수정된 버전이 곧 릴리즈될 예정입니다. 감사합니다.

**Comment by admin0319** [comment]
확인 감사합니다! 릴리즈 후에 다시 해볼께요~ ^^
