### ISSUE TITLE
Flow와 Flow를 연결 사용할 수 있나요? 

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#624]
첫번 째 Flow는 입력데이타 없이 작업후 Delete function으로 작업하여
잘 처리가 되었는 데 두 번째 Flow에서 입력 데이타 정의를 어떻게 해야 하는 지 
몰라 처리가 되지 않네요.

혹시, 방안이 있을까요?

![image](https://user-images.githubusercontent.com/32014177/62184232-1332ad80-b398-11e9-80cd-7f2733b37eb3.png)

**Comment by biue8765** [comment]
Flow와 Flow는 연결해서 사용하실 수 있습니다.
입력 데이터는 함수와 함수 연결시에 자동으로 두번째 flow에서도 input data로 보이게 됩니다.
![flow와flow연결](https://user-images.githubusercontent.com/44859963/62676186-e5c3b080-b9e4-11e9-8d57-1063b91e1313.PNG)

말씀하시는 궁금한 사항이, flow와 flow간 direct 연결이시라면,
1. 아래 flow-1 모델에서 결과값을 오른쪽 Return Data탭의 Out Data List에서 Selected Data로 drag&drop해서 올려주십시오.
![flow-1결과값](https://user-images.githubusercontent.com/44859963/62676304-62ef2580-b9e5-11e9-8bb4-e0d9bc35ef55.PNG)
2. 뒤에 연결할 flow-2 모델에서 왼쪽 Input Data탭의 In Data List에서 Selected Data로 drag&drop해서 올려주십시오.
![flow-2입력값](https://user-images.githubusercontent.com/44859963/62676359-929e2d80-b9e5-11e9-9e56-6de833fdfb84.PNG)
3. flow-1과 flow-2가 있는 모델에서 이제 두 함수를 연결해주시면, flow-1의 결과값을 flow-2의 입력값으로 사용하여 모델링을 하실 수 있습니다.
