### ISSUE TITLE
Python Tensorflow 설치 문의(Ubuntu)

### ISSUE THREAD

**Issue by admin0319** [brightics/studio#636]
이 문서를 참조하여 윈도우에서는 성공했습니다.
ubuntu 16.04에서는 어떻게 적용할 수 있을까요?
가이드 부탁드립니다.
감사합니다.

_Originally posted by @admin0319 in https://github.com/brightics/studio/issues/561#issuecomment-517623646_

**Comment by krazyeom** [comment]
cd brightics-studio/lib/brightics_python_env
. bin/activate 

python env가 활성화 되면서 아래와 같이 프롬프트가 바뀝니다.
`(brightics_python_env) [brightics@TEST:/home/brightics/brightics-studio/lib/brightics_python_env]`

이후 
pip install tensorflow 으로 설치를 하면 됩니다.

**Comment by admin0319** [comment]
답변 감사합니다.

**Comment by admin0319** [comment]
답변 감사합니다.

**Comment by admin0319** [comment]
답변 감사합니다.
