### ISSUE TITLE
기존 함수 입력 파라미터 변수 설정 질문

### ISSUE THREAD

**Issue by phg0804** [brightics/studio#639]
기존 함수에서 입력값으로 상수가 아닌 변수를 사용하는 방법이 있나요?
예를 들면 Random Forest Regression Train같은 함수를 사용할 때
Number of Trees같은 입력값에 상수만 입력가능한데, 
화면 좌측 Variables 탭에서 정의한 변수(ntree)를 사용할 수는 없는 것인지요?
![KakaoTalk_Photo_2019-08-06-22-29-51](https://user-images.githubusercontent.com/14102433/62543952-d4ba5880-b899-11e9-924e-92d2a2612683.png)

**Comment by krazyeom** [comment]
현재는 사용할 수 없습니다.  
* 추가 공모전으로 질문은 공모전 홈페이지를 통해서 질문 부탁드립니다.
