### ISSUE TITLE
brightics studio에 tensorflow 연동

### ISSUE THREAD

**Issue by DuckJoongLee** [brightics/studio#640]
안녕하세요
brightics studio안에서
python script 노드로 tensorflow 패키지를 사용하고 싶은데 연동이 안되고 있어 질문을 드립니다

현재 파이썬 버전은 3.7.3에 아나콘다3로 설치하였고 주로 파이참으로 사용했습니다

저는 주로 노트북에서 구현 하는 데
cmd로 실행 하여 brightics-studio 폴더 안에 python 경로로 들어간 뒤 pip install tensorflow를 입력하였습니다 
그래서 일단 설치가 되었지만 경고가 뜬 상태로 install이 되었고 brightics-studio에서는 tensorflow 모듈을 찾을 수 없다고 나옵니다.
(brightics-studio\lib\python\Lib\site-packages에서는 tensorflow 1.14버전이 깔아져 있는 상태입니다)

또 다른 방법으로 
brightics-studio안에 python36.pth 파일을 파이참으로 열어서 경로를 
아나콘다3 tensorflow와 keras가 설치되어있는 가상환경 경로랑 연동을 하여 실행했는데

brightics-studio에서 run을 했을 때 시간만 지나고 로딩만 지속되면서 결과가 나오질 않습니다

파이썬 버전의 문제일까요?

**Comment by krazyeom** [comment]
https://github.com/brightics/studio/issues/561 를 참조해서 설치 바랍니다. 

참고적으로 Brightics Studio는 python 3.6 버전을 사용하고 있습니다.

**Comment by ezcyber** [comment]
window에서는  python36._pth를 이용하여 site_package를 Import하였는 데도
Brightics에서 계속 Error가 나네요.

Tensorflow numpy 충돌로 보이네요. 
 --> 이문제에 대한 해결책은 찾지 못했네요.

Pytorch의 경우, 문제가 없어서 Tensorflow대신 Pytorch로 코드 변환하여 작업중입니다.

혹시, Tensorflow와 연동이 되면 알려주세요.

**Comment by DuckJoongLee** [comment]
일단 해결은 했습니다

파이썬 3.6.8 버전, tensorflow 1.12.0 버전을 깔았고
cmd으로 파이썬 3.6.8안에서 tensorflow와 필요한 패키지를 install하였습니다

그런 다음

python36._pth에서 PATH를 tensorflow가 깔린 파이썬 3.6.8 site-packages로 수정한 다음 
brightics studio에서  tensorflow를 실행 하였습니다

**Comment by ezcyber** [comment]
위 환경과 동일하게  Tensorflow를 설치하였는 데
 python 에서는   warning 
Brighitcs에서는 여러 함수에서  Error  가 나오네요.

AutoEncoder 정도의 기능을 사용하고 있어서 Pytorch로 간단히 전환하고 있네요.

![image](https://user-images.githubusercontent.com/32014177/62910429-66a2f380-bdbb-11e9-94e5-6ea7da1e782a.png)


![image](https://user-images.githubusercontent.com/32014177/62910445-76bad300-bdbb-11e9-8d2f-a7a7e53be08e.png)

**Comment by DuckJoongLee** [comment]
혹시 brightics studio에서 python script로 
import tensorflow를 출력하면 저런 error가 나오시는 건가요?
cmd창에서는 저도 비슷한 warning이 나오는데 
brightics studio에서는 돌아가거든요
numpy랑 충돌은... 방법을 모르겠습니다

import keras도 error가 나오시나요?

**Comment by krazyeom** [comment]
#561 여기에서는 해결하셨다고 하셨는데 또 발생한건가요?

**Comment by ezcyber** [comment]
저의 경우, Pytorch로는 해결,  Tensorflow에서는 미해결입니다.

**Comment by krazyeom** [comment]
@ezcyber  

#561 여기에서는 해결 
```
Anaconda환경에서는 되지 않아 Python을 설치후 tensorflow Ver.을 1.12.0으로 설치하여 해결하였습니다.설비 Log에 Autoencoder를 구현
```

이후 또 에러가 난건가요?

**Comment by krazyeom** [comment]
c:\brightics-studio\lib\python>python get-pip.py
c:\brightics-studio\lib\python\Scripts>pip install --upgrade numpy==1.17.0
c:\brightics-studio\lib\python\Scripts>pip install tensorflow==1.13.1

Brightics에 tensorflow 1.13.1과 numpy 1.17.0 으로 하면 아래와 같이 잘 동작을 합니다. 

![image](https://user-images.githubusercontent.com/442477/63659280-8e4a8080-c7eb-11e9-9383-7a82f8ac694e.png)

**Comment by krazyeom** [comment]
외부 python 외에 Brightics Python 에 아래와 같이 numpy와 tensorflow을 설치해서 테스트 해봤습니다.  아래 케이스(tensorflow==1.13.1)의 경우에는 numpy 버전이 달라져서 brightics 함수가 정상 동작 안할수도 있습니다. 

c:\brightics-studio\lib\python>python get-pip.py

c:\brightics-studio\lib\python\Scripts>pip install numpy==1.15.2
c:\brightics-studio\lib\python\Scripts>pip install tensorflow==1.10
![image](https://user-images.githubusercontent.com/442477/63660559-e3899080-c7f1-11e9-8db1-e451003b6c92.png)

c:\brightics-studio\lib\python\Scripts>pip install numpy==1.17.0
c:\brightics-studio\lib\python\Scripts>pip install tensorflow==1.13.1
![image](https://user-images.githubusercontent.com/442477/63660486-a32a1280-c7f1-11e9-8ed2-088db436b01e.png)

**Comment by krazyeom** [comment]
Brightics 와 외부 python 연결은 python 버전 library 에 따라 안되는 경우가 발생할 수 있습니다. 이점 확인하시고 사용하길 부탁드립니다.

**Comment by smeil123** [comment]
```
brightics-studio\lib\python\Scripts> pip list
Package              Version
-------------------- -------
absl-py              0.8.0
astor                0.8.0
gast                 0.2.2
google-pasta         0.1.7
grpcio               1.23.0
h5py                 2.9.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
Markdown             3.1.1
mock                 3.0.5
numpy                1.16.4
pandas               0.25.1
pip                  19.2.3
protobuf             3.9.1
python-dateutil      2.8.0
pytz                 2019.2
setuptools           41.2.0
six                  1.12.0
tensorboard          1.12.2
tensorflow           1.12.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
Werkzeug             0.15.5
wheel                0.33.6
wrapt                1.11.2

brightics-studio\lib\python\Scripts> python -c "import tensorflow as tf;print(tf.reduce_sum(
tf.random.normal([1000, 1000])))"
Tensor("Sum:0", shape=(), dtype=float32)
```


이렇게 실행결과가 나오고
brightics-studio/python/Scripts의 python에서 tensorflow를 실행시킬때는 되는데
브라이틱스 스튜디오에서는 여전히 안됩니다 ㅠㅠ

해결방법을 알려주세요

위에서 말씀하신 
`c:\brightics-studio\lib\python>python get-pip.py

c:\brightics-studio\lib\python\Scripts>pip install numpy==1.15.2
c:\brightics-studio\lib\python\Scripts>pip install tensorflow==1.10

c:\brightics-studio\lib\python\Scripts>pip install numpy==1.17.0
c:\brightics-studio\lib\python\Scripts>pip install tensorflow==1.13.1
`
이버전들도 다 설치해봤는데 안됩니다

**Comment by krazyeom** [comment]
여전히 안 된다는 것을 자세히 설명해주세요. 어떻게 했는지요.
