### ISSUE TITLE
폴더 내의 모든 파일을 업로드할 수 있는 방법이 있나요??

### ISSUE THREAD

**Issue by kkwinwin** [brightics/studio#642]
여러개의 엑셀파일을 Brightics로 불러와서 합치려고 하는데 하나하나 옮기는 것이 아니라 한번에 옮길 수 있는 방법이 있나요??

**Comment by krazyeom** [comment]
다량의 파일을 한 번에 올리는 기능은 없습니다. Brightics의 python script를 이용해서 load또는 read csv 함수를 사용하면 비슷한 기능을 구현할수 있을 겁니다.
