### ISSUE TITLE
Wrong feature selection 

### ISSUE THREAD

**Issue by arcontechnologies** [brightics/studio#643]
Hi (I'm new to Brightics studio),

I have a dataset of 13 columns but when I want to perform a logistic regression by selecting 12 of 13 as input feature columns, I only can see 2 of them.
What am I doing wrong ?

Thanks for your feedback.

![image](https://user-images.githubusercontent.com/17960609/63226798-09ee7100-c1df-11e9-8e54-6a28d9e5fd60.png)

**Comment by power4454** [comment]
We don't support string column as a feature column. But you can do this with one hot encoder alternatively.

**Comment by arcontechnologies** [comment]
Ok Thanks. I got it
