### ISSUE TITLE
Histogram 그래프의 x축 숫자가 보이지 않습니다.

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#646]
숫자가 중첩되어 알아 볼수가 없는 데 
어떻게 조치하면 될까요?

![image](https://user-images.githubusercontent.com/32014177/63239185-ff86b280-c284-11e9-934c-95fbc3e018dd.png)

**Comment by krazyeom** [comment]
확인해보니, 다른 차트에는 Axis Label에서 Label의 각도를 설정할 수 있는데요. Histogram은 빠져있습니다. 버그 리포트 했습니다.

**Comment by ezcyber** [comment]
Label 각도 설정해도,  축의 값이 너무 많이 나와요
