### ISSUE TITLE
brightics함수로 만든 모델(SVM, RandomForest 등등)을 python script에서 사용할 수 있는 방법이 있나요??

### ISSUE THREAD

**Issue by kkwinwin** [brightics/studio#650]
brightics로 만든 모델(SVM, RandomForest)을 학습 후 내장 함수로 predict하는 것이 아니라 python script로 predict을 하고 싶은데 script에서 brightics로 만든 모델을 불러올 수 있는 방법이 있나요??

**Comment by krazyeom** [comment]
없습니다.

**Comment by power4454** [comment]
가능하기는 합니다.
brightics-studio\brightics-server\functions\python\brightics\function\classification\svm_classification.py 코드를 보시면 _model['svc_model'] = _svc_model란 것이 있는데
svc_model이란 곳에 fit한 정보가 들어있단 뜻입니다.

즉 python script에서
