### ISSUE TITLE
테이블 Col에 라벨을 한글로 하려면

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#653]
테이블 변수가 많아 영문으로 관리하기가 어려운데
한글로 라벨을 줄수 있는 방법이 있을까요?

DB에서 Description과 같은 역할로 사용하려면

![image](https://user-images.githubusercontent.com/32014177/63746156-1198ce80-c8df-11e9-837c-be62db466ad1.png)

**Comment by krazyeom** [comment]
Description 기능은 없습니다.
