### ISSUE TITLE
Correlation 결과가 6개 변수만 나와요

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#654]
상관분석 을 14개의 변수로 하였는 데 결과가 6개의 결과만 나와요

![image](https://user-images.githubusercontent.com/32014177/63750903-4ad63c00-c8e9-11e9-88b7-c33ba8414d13.png)

![image](https://user-images.githubusercontent.com/32014177/63750979-7ce79e00-c8e9-11e9-8ce7-70c940e26182.png)

**Comment by hyoxt121** [comment]
안녕하세요. 
위의 결과는 correlation 값이 nan이 나온 것으로 정확한 원인을 위해서는 데이터를 공유해 주셔야 합니다.. 가능성으로는 데이터에 nan이 있거나 null이 있는 경우입니다.
