### ISSUE TITLE
python script에서 사용자 정의 class import 방법

### ISSUE THREAD

**Issue by lkc9999** [brightics/studio#655]
python 스크립트 사용시 별도로 정의해둔 python 코드를 import 하여 사용하는 방법이 있는지 문의 드립니다.
방법이 있다면 가이드 부탁드립니다.

감사합니다.

**Comment by krazyeom** [comment]
#561 를 참조해서 우선 PYTHONPATH를 잡으면 됩니다. 이후 brightics python script에서 import하면 됩니다. 

linux & mac은 PYTHONPATH에 추가하면 됩니다.
