### ISSUE TITLE
생성된 Report 삭제문의

### ISSUE THREAD

**Issue by seongsu-kim** [brightics/studio#658]
제목과 같이 생성된 Report에서 일부페이지를 삭제하고자 합니다.

Report 상단 Delete Page 삭제를 하였으나 재접속 시 삭제되지않고 그대로 남아있습니다.

어떻게 해야 완전히 삭제가 가능한가요?

**Comment by krazyeom** [comment]
테스트를 해보니 정상적으로 삭제가 되고 있습니다. 
즉시 삭제 및 F5로 재접속을 해도 삭제 처리 된 것으로 확인됩니다. 

다시 확인 부탁드립니다.

**Comment by seongsu-kim** [comment]
다시 확인하여도 동일한 증상입니다. 혹시나하여 버전도 만들어보았으나 삭제가 되지 않습니다.
제가 한 절차를 다시 적어보겠습니다.
모델선택 -> Report Open -> 특정페이지삭제 -> 탭닫기 -> 크롬탭에서 X로 닫을 경우 (변경사항이 저장 안 될수도 있다는 메시지가 나옴) -> 크롬탭에서 닫지 않고 로그아웃 -> 재접속 -> Report Open 시 페이지 삭제되지 않음

혹시나하여 삭제 후 버전도 생성해보았으나 동일한 증상입니다. 
다시 확인 부탁드립니다.

**Comment by seongsu-kim** [comment]
해결하였습니다. 

삭제대상 페이지에 연결이 안된(chrome console에서 400 에러발생) 데이터소스가 있는 경우 삭제가 되지 않는 현상입니다.
삭제대상 페이지에 있는 모든 항목을 삭제하고 데이터소스도 삭제한 후 페이지를 삭제하면 정상적으로 처리가 되네요....

페이지의 컨텐츠와 관계없이 삭제가 되야될듯합니다.!!!!

**Comment by krazyeom** [comment]
넵, 버그 리포팅해서 반영하도록 하겠습니다.
