### ISSUE TITLE
Read from DB 내 mysql date_format 사용 오류

### ISSUE THREAD

**Issue by philius5** [brightics/studio#660]
mysql db 접속하여 timestamp로 읽어와지는 date 값을 date_format 을 이용해서 날짜로 변환하고자 합니다.
pymysql을 내부적으로 사용하는 관계로 date_format(col, '%%Y-%%m-%%d) 로 적용을 하였으나,
contains invalid character(s) among ' ,;{}()\n\t=' 오류가 발생합니다.
해당 쿼리는 타 query editor에서 모두 정상 동작되는 쿼리 입니다.
timestamp 값으로 출력되는 값을 변환 하고 싶습니다.

**Comment by krazyeom** [comment]
저 에러메세지는 column name에서 ,;{}()\n\t= 가 포함되었을 때 나오는 에러메세지인데 변환하려는 column name이 어떻게 되나요?

**Comment by philius5** [comment]
column name은 t.requestdate 이고 date_format으로 아래 내용과 같이 변환하려고 합니다.
date_format(t.requestdate, '%%Y-%%m-%%d') 입니다.

**Comment by philius5** [comment]
해결했습니다. column name에 alias를 주니 출력 되었습니다.
