### ISSUE TITLE
Tutorial: Auto classification

### ISSUE THREAD

**Issue by lucnap** [brightics/studio#670]
Hello, I can't follow your tutorial because it is not clear.
How do I distinguish the 34 competence variables? I tried starting from Acceleration until Volleys + preferred_foot_Right + Age,  but the result of the Dendogram is not like yours.

I tried to import the model downloaded from your site but nothing works as I show in the picture.
![image](https://user-images.githubusercontent.com/3464029/66274962-4efc5e80-e884-11e9-8628-f13deba7b538.png)

I'm using BrighticsStudio-v1.1-2019.09-windows

**Comment by krazyeom** [comment]
http://brightics.ai/docs/ai/v3.6/tutorials/302_2_fifa_classification_model?type=insight
I think you used an AI 3.6 version of tutorials on Brightics.ai. Brightics Studio cannot import and use that version.

You have to use Studio 1.0 of the tutorial on the site. http://brightics.ai/docs/ai/s1.0/tutorials/01_py_add_localdata
There are fewer types of tutorials than AI 3.6.

![image](https://user-images.githubusercontent.com/442477/66372596-55541d00-e9e1-11e9-87ef-75a676f3e3f3.png)

**Comment by lucnap** [comment]
Thanks, I will follow tutorials for Studio 1.0

**Comment by krazyeom** [comment]
Thanks, 
If you have any questions, please feel free to leave a message.
