### ISSUE TITLE
Random forest의 Tree수 제약 확인

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#674]
Random forest에서 Tree수를 200개인 경우는 Error발생되지 않는 데
500개하면 error가 발생되면서 시스템이 구동이 되지 않아요

Random forest수에 한계가 있나요?

어떻게 조치할수 있나요?
아래에  Log를 그대로 보내드립니다.

JOB ID: c_jetIiQgH2mk36rwL_201910221907096280
java.lang.Exception: py4j.protocol.Py4JError: An error occurred while calling t.putToKVStore

	at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.run(PythonProcessManager.java:279)
	at com.samsung.sds.brightics.agent.context.python.PythonProcessManager.run(PythonProcessManager.java:236)
	at com.samsung.sds.brightics.agent.context.python.PythonContext.runFunction(PythonContext.java:72)
	at com.samsung.sds.brightics.agent.service.TaskService.executeFunction(TaskService.java:203)
	at com.samsung.sds.brightics.agent.service.TaskService.executeTaskToContext(TaskService.java:165)
	at com.samsung.sds.brightics.agent.service.TaskService.getTaskResult(TaskService.java:115)
	at com.samsung.sds.brightics.agent.service.TaskService$1.run(TaskService.java:83)
Caused by: java.lang.Throwable: <function _group at 0x0000027F6468C730> elapsed time: 0.031272172927856445 s
Number of groups: 18
group_by: ['PROCESS_NO']
group_key_dict: {'01_NP-1': ['01_NP-1'], '02_NP-2 (2P)': ['02_NP-2 (2P)'], '03_NP-2 (3P)': ['03_NP-2 (3P)'], '05_수축': ['05_수축'], '10_PU': ['10_PU'], '14_W/F 용출': ['14_W/F 용출'], '16_SLICE': ['16_SLICE'], '17_M/BUFFING': ['17_M/BUFFING'], '19_염색 (수세)': ['19_염색 (수세)'], '20_염색': ['20_염색'], '23_PAD 건조': ['23_PAD 건조'], '24_PAD 건+약': ['24_PAD 건+약'], '27_F/BUFFING (이면)': ['27_F/BUFFING (이면)'], '29_F/BUFFING (양면)': ['29_F/BUFFING (양면)'], '30_F/BUFFING (BRUSH)': ['30_F/BUFFING (BRUSH)'], '31_F/BUFFING': ['31_F/BUFFING'], '32_PAD 폭SET': ['32_PAD 폭SET'], '33_COATING (Gravure)': ['33_COATING (Gravure)']}
_sample_result is running
_sample_result for group 01_NP-1 is running.
_sample_result finished.
<function _sample_result at 0x0000027F6468C8C8> elapsed time: 0.5937495231628418 s
_function_by_group_key is running
_function_by_group_key for group 01_NP-1 is running.
_function_by_group_key for group 02_NP-2 (2P) is running.
_function_by_group_key for group 03_NP-2 (3P) is running.
_function_by_group_key for group 05_수축 is running.
_function_by_group_key for group 10_PU is running.
_function_by_group_key for group 14_W/F 용출 is running.
_function_by_group_key for group 16_SLICE is running.
_function_by_group_key for group 17_M/BUFFING is running.
_function_by_group_key for group 19_염색 (수세) is running.
_function_by_group_key for group 20_염색 is running.
_function_by_group_key for group 23_PAD 건조 is running.
_function_by_group_key for group 24_PAD 건+약 is running.
_function_by_group_key for group 27_F/BUFFING (이면) is running.
_function_by_group_key for group 29_F/BUFFING (양면) is running.
_function_by_group_key for group 30_F/BUFFING (BRUSH) is running.
_function_by_group_key for group 31_F/BUFFING is running.
_function_by_group_key for group 32_PAD 폭SET is running.
_function_by_group_key for group 33_COATING (Gravure) is running.
_function_by_group_key finished.
{'model': {'_grouped_data': {'data': {'01_NP-1': {'classifier': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='log2', max_leaf_nodes=None,
            min_impurity_decrease=0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=100, verbose=0, warm_start=False), 'params': {'feature_cols': ['PRODUCT_RATIO_PER_HOUR', 'LENGTH', 'WEIGHT', 'THICKNESS', 'WIDTH', 'UNIT_WEIGHT', 'DENSITY', 'LENGTH_EXPANTION_RATIO', 'WIDTH_COMPRESS_RATIO', 'THINKNESS_CHANGE_RATIO'], 'label_col': 'SEC_01', 'n_estimators': 500, 'criterion': 'gini', 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'min_weight_fraction_leaf': 0, 'max_features': 'log2', 'max_leaf_nodes': None, 'min_impurity_decrease': 0, 'class_weight': None, 'random_state': 100}, '_repr_brtc_': {'contents': [{'text': "\n ## Random Forest Classification Train Result\n\n ### Parameters\n - feature_cols: ['PRODUCT_RATIO_PER_HOUR', 'LENGTH', 'WEIGHT', 'THICKNESS', 'WIDTH', 'UNIT_WEIGHT', 'DENSITY', 'LENGTH_EXPANTION_RATIO', 'WIDTH_COMPRESS_RATIO', 'THINKNESS_CHANGE_RATIO']\n- label_col: SEC_01\n- n_estimators: 500\n- criterion: gini\n- max_depth: None\n- min_samples_split: 2\n- min_samples_leaf: 1\n- min_weight_fraction_leaf: 0\n- max_features: log2\n- max_leaf_nodes: None\n- min_impurity_decrease: 0\n- class_weight: None\n- random_state: 100\n\n ### Feature Importance\n ![image]    ", 'type': 'md'}]}, 'feature_importance_table':              feature_name  importance
0  PRODUCT_RATIO_PER_HOUR    0.170011
1                  LENGTH    0.195164
2                  WEIGHT    0.155173
3               THICKNESS    0.058816
4                   WIDTH    0.071625
5             UNIT_WEIGHT    0.140984
6                 DENSITY    0.208228
7  LENGTH_EXPANTION_RATIO    0.000000
8    WIDTH_COMPRESS_RATIO    0.000000
9  THINKNESS_CHANGE_RATIO    0.000000}}, 'group_by': ['PROCESS_NO'], 'group_key_dict': {'01_NP-1': ['01_NP-1'], '02_NP-2 (2P)': ['02_NP-2 (2P)'], '03_NP-2 (3P)': ['03_NP-2 (3P)'], '05_수축': ['05_수축'], '10_PU': ['10_PU'], '14_W/F 용출': ['14_W/F 용출'], '16_SLICE': ['16_SLICE'], '17_M/BUFFING': ['17_M/BUFFING'], '19_염색 (수세)': ['19_염색 (수세)'], '20_염색': ['20_염색'], '23_PAD 건조': ['23_PAD 건조'], '24_PAD 건+약': ['24_PAD 건+약'], '27_F/BUFFING (이면)': ['27_F/BUFFING (이면)'], '29_F/BUFFING (양면)': ['29_F/BUFFING (양면)'], '30_F/BUFFING (BRUSH)': ['30_F/BUFFING (BRUSH)'], '31_F/BUFFING': ['31_F/BUFFING'], '32_PAD 폭SET': ['32_PAD 폭SET'], '33_COATING (Gravure)': ['33_COATING (Gravure)']}}}}
['01_NP-1', '02_NP-2 (2P)', '03_NP-2 (3P)', '05_수축', '10_PU', '14_W/F 용출', '16_SLICE', '17_M/BUFFING', '19_염색 (수세)', '20_염색', '23_PAD 건조', '24_PAD 건+약', '27_F/BUFFING (이면)', '29_F/BUFFING (양면)', '30_F/BUFFING (BRUSH)', '31_F/BUFFING', '32_PAD 폭SET', '33_COATING (Gravure)']
<function _function_by_group at 0x0000027F6468C620> elapsed time: 11.719151020050049 s
Traceback (most recent call last):
  File "D:\SW_Install\brightics-studio\brightics-server\functions\python\brightics\brightics_python_runner.py", line 128, in _executer
    exec(interactive_code_object, self._globals)
  File "<string>", line 8, in <module>
  File "D:\SW_Install\brightics-studio\brightics-server\functions\python\brightics\brightics_data_api.py", line 145, in write_data
    KVStoreClient.set(key, data_info['data'])
  File "D:\SW_Install\brightics-studio\brightics-server\functions\python\brightics\brightics_kv_store_client.py", line 24, in set
    gateway.put_kv_data(key, data_json.to_json(data, for_redis=True))
  File "D:\SW_Install\brightics-studio\brightics-server\functions\python\brightics\brightics_java_gateway.py", line 132, in put_kv_data
    self._gateway.entry_point.putToKVStore(key, data)
  File "D:\SW_Install\brightics-studio\lib\python\Lib\site-packages\py4j\java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "D:\SW_Install\brightics-studio\lib\python\Lib\site-packages\py4j\protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling t.putToKVStore
	... 7 more

**Comment by hyoxt121** [comment]
tree 갯수 재한은 없고 메모리를 좀더 큰 환경해서 테스트해보시기 바랍니다.

**Comment by krazyeom** [comment]
windows 환경 같은데요. 램이 얼마나 되나요?

**Comment by ezcyber** [comment]
32기가이고요 
Error가 나서 Memory를 모니터링했는데
memory에는 큰 변화가  없어요
​
-----Original Message-----

**Comment by ezcyber** [comment]
다른 노드로 동작되지 않아서 Launcher를 재기동해야 하네요.

그리고 C:\brightics\brightics-studio\brightics-server에 java_pid?.hprof라는 파일이 어마한 사이즈로
생성이 되어 있네요.
![image](https://user-images.githubusercontent.com/32014177/67457163-dbbd5f80-f66d-11e9-9d8e-eeb198d3b368.png)

**Comment by ezcyber** [comment]
java_pid.hprof라는 파일삭제후 launcher 재기동을 매번하다가 Tree숫자는 작게해서
사용하고 있어요.

**Comment by krazyeom** [comment]
java 가 oom 나면서 생긴 파일이니 지우셔도 됩니다. 데이터 크기와 tree size 때문에 그럴수 있습니다.

**Comment by ezcyber** [comment]
데이타 크기가 10만개 정도이고 X 변수는 20개이며, 그룹은 50개 정도입니다.
Tree수를 500개 정도할 경우, Random Forest 작업을 하려면 메모리 사이즈를 얼마나해야 하나요?
