### ISSUE TITLE
Multi-Chart 기능이 안보여요

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#675]
Multi-Chart 기능이 보이지 않는데 어떻게 해야 사용할 수 있나요?

![image](https://user-images.githubusercontent.com/32014177/67458376-05c45100-f671-11e9-98eb-8f9044fda768.png)

**Comment by ezcyber** [comment]
Multi-Chart의 활용이 많아 어떻게 할지 고민하고 있습니다.

현재 Ver.에서 Multi-Chart를 지원하지 않는 것인지 아니면 누락되어 차기 Ver.에서 지원할 것인지 
알고 싶습니다.

**Comment by krazyeom** [comment]
다음 릴리스 때 다시 복원될 예정입니다.

급하시면 `brightics-studio\visual-analytics\public\css\va\brightics-va.css` 파일을 여시고, 1116~1119 라인을 삭제하시고 F5으로 reload 하면 다시 보이게 됩니다. 

```
.bcharts-ws-panel-toolitem[action="multichart"]
{
    display: none !important;
}
```
