### ISSUE TITLE
UDF 생성기에서의 마우스 Scroll 동작 오류

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#676]
Parameter를 추가한후 하단의 window영역으로의 마우스 Scroll이 되지 않아요.

저만 그런가요?

![image](https://user-images.githubusercontent.com/32014177/67550234-eac11200-f740-11e9-8da5-aba820a4aae1.png)

![image](https://user-images.githubusercontent.com/32014177/67550166-c49b7200-f740-11e9-930e-cbb8170b7e97.png)

**Comment by krazyeom** [comment]
네, chrome 스펙이 변경되면서 생긴 오류였습니다.
최신 버전에는 버그 패치 되어 있습니다. 사용하고 있는 버전이 언제적건가요?

**Comment by ezcyber** [comment]
최신 버전에서는 문제가 없네요.
Multi-Chart문제로 이전 ver.을 사용하고 있습니다.

감사합니다.

**Comment by krazyeom** [comment]
Windows 최신 버전의 Brightics Launcher는 자동 업데이트 기능이 있으니 받아두시면 좋습니다.
