### ISSUE TITLE
questions about spark support

### ISSUE THREAD

**Issue by yuanbw** [brightics/studio#696]
does the open source brightics studio support spark on yarn? such as spark on cloudera cluster.
which versions does it support? Or just Stand-alone calculation?

**Comment by power4454** [comment]
Only Enterprise version supports spark.

**Comment by krazyeom** [comment]
We don't have any plan to support Spark on Brightics Studio. but we provide Brightics AI which is a commercial and Enterprise version. You can try a trial version on https://trial.brightics.ai
