### ISSUE TITLE
엑셀 다운로드시, 열 구분이 안되네요.

### ISSUE THREAD

**Issue by jackhstar** [brightics/studio#698]
스튜디오 2019.11 버젼에서 엑셀 다운로드 시, 열 구분이 안 되고
(tab 등으로 구분지었습니다만)
하나의 열로 나타납니다.

**Comment by krazyeom** [comment]
엑셀 다운로드라는 것을 정확하게 설명 부탁드립니다.

**Comment by krazyeom** [comment]
정확하게는 Brightics Studio는 엑셀 다운로드기능은 없고 csv 다운로드 기능이 있어 그것으로 해보았습니다. 

,로 구분했을 때, tab으로 구분했을 때 모두 정상 동작하는 것을 확인했습니다. 

![image](https://user-images.githubusercontent.com/442477/68906748-b6ad9f80-0788-11ea-9601-1f4cccdb7585.png)

![image](https://user-images.githubusercontent.com/442477/68906787-d9d84f00-0788-11ea-9b70-eb9459270d6a.png)

![image](https://user-images.githubusercontent.com/442477/68906816-f4aac380-0788-11ea-8a37-668e421819f0.png)
