### ISSUE TITLE
2019.11버전 Latent Dirichlet Allocation 실행시 결과테이블의 컬럼명 오류 

### ISSUE THREAD

**Issue by lkc9999** [brightics/studio#700]
Latent Dirichlet Allocation 실행후 결과 테이블의 컬럼(top topic)이 스페이스바가 포함되어 
이후 펑션을 연결하여 진행이 불가합니다.

![Image 2](https://user-images.githubusercontent.com/47658184/69199740-433ad200-0b7c-11ea-9960-0644bf8d8efd.png)

추가로 Latent Dirichlet Allocation 펑션에 Hold column 기능(인풋 데이터 컬럼을 결과 테이블에 가지고 오는 기능)이 추가 가능한지 문의드립니다.

**Comment by hyoxt121** [comment]
네 함수 output column 명을 수정하도록 하겠습니다
