### ISSUE TITLE
2019. 11 Latent Dirichlet Allocation 분류결과 문의

### ISSUE THREAD

**Issue by lkc9999** [brightics/studio#701]
안녕하세요 2019 11 버전에있는 Latent Dirichlet Allocation 기능을 사용중인데 문의사항이 있습니다.

인풋데이터는 총 968 행이고 Latent Dirichlet Allocation의 설정에서
Number of Topic을 100
Number of Terminologies를 100으로 설정 후 실행(나머지설정은 default)하면
총 31개의 Topic으로 분류되는데 100개의 토픽으로 분류가 되지않는 이유를 알고 싶습니다.

**Comment by hyoxt121** [comment]
안녕하세요.
Number of Topic이 100이면 무조건 100개의 topic으로 분류가 되는 것은 아니고 최대 100개 topic 까지 분류가 됩니다
