### ISSUE TITLE
2019.11버전 Penalized Linear Regression Train 결과 관련

### ISSUE THREAD

**Issue by slpmee** [brightics/studio#702]
model 탭에 예측결과(모든 행에 대한 y_hat 값) 가 다 표시되는데 table 탭으로 별도 나오는게 맞지 않을까 싶습니다. 너무 많은 데이터가 출력되면 브라우저가 멈추어서요.

**Comment by hyoxt121** [comment]
네 맞습니다. 이것도 수정해 드리겠습니다.

**Comment by hyoxt121** [comment]
네 맞습니다. predict에서 나오는 값이라 삭제하도록 하겠습니다

**Comment by krazyeom** [comment]
It was already resolved.
