### ISSUE TITLE
R을 연동하여 사용할 수 있나요?

### ISSUE THREAD

**Issue by ezcyber** [brightics/studio#703]
R Code를 이용하여 사용하고자 하는 데
어떻게 해야 하나요?

**Comment by power4454** [comment]
rpy2라는 패키지를 설치하시면 python으로 R 코드를 돌릴 수는 있습니다. 현재 enterprise버전에서는 java의 Rconnection과 spark을 이용한 분산 R script 함수가 제공되고 있고 곧 rpy2를 이용한 R script 함수가 제공될 예정이라 python script처럼 활용할 수 있지만 스튜디오는 계획이 없습니다. 감사합니다.
