### ISSUE TITLE
There is no parameter validation step for 'add function column'

### ISSUE THREAD

**Issue by slpmee** [brightics/studio#708]
When I enter no value in  [new column name] of 'Add function column',  the function isn't ended and there is no error message. 

This function usually ends in one second on this model.

![image](https://user-images.githubusercontent.com/18569006/69839834-8f80c300-129c-11ea-9ff6-d9cb4e4d11f4.png)

**Comment by krazyeom** [comment]
Could put a column name in ‘New Column Name’?

**Comment by slpmee** [comment]
Thanks. I just forgot to fill in the blank. It works fine now.

**Comment by power4454** [comment]
We fix this validation issue on #705. It will be updated next version.
