### ISSUE TITLE
함수의 parameter를 variable로 등록할 때 데이터 타입이 일치하지 않는 현상

### ISSUE THREAD

**Issue by jinhwanhan** [brightics/studio#730]
![202002061830610_DCBHTJ0C](https://user-images.githubusercontent.com/44860521/74137342-f9213400-4c32-11ea-9cf2-dc443a1786b0.jpg)

함수의 parameter를 variable로 등록할 때 데이터 타입이 일치하지 않는 현상이 있습니다.

예를 들어 K-Means 함수의 경우, Number of Clusters를 variable로 등록하게 되면 이 variable의 타입이 string으로 세팅되는데, 실제 함수에서 요구하는 타입은 integer 형태이기 때문에 variable의 타입을 따로 변경하지 않는다면 함수를 실행할 때 타입 불일치 에러가 발생합니다.
variable을 등록할 때 parameter와 동일한 타입으로 등록되었으면 좋겠습니다.

**Comment by krazyeom** [comment]
![image](https://user-images.githubusercontent.com/442477/89501076-b31de500-d7fd-11ea-9ccf-84ed5cf75ced.png)

Number 타입으로 변경하니 잘 동작합니다. 사용성의 문제가 있긴 하나 모든 파라미터를 유동적으로 변경하기는 힘듭니다. 

추후에 다시 고려해보겠습니다.
