### ISSUE TITLE
Add Function Column) - Help Expression Type is incorrect.

### ISSUE THREAD

**Issue by shovsj** [brightics/studio#74]
![image](https://user-images.githubusercontent.com/37683852/49496523-89cee800-f8a9-11e8-9bcd-d62e7613d027.png)

**Comment by shovsj** [comment]
![image](https://user-images.githubusercontent.com/37683852/49497517-f64ae680-f8ab-11e8-9665-d6967a316a01.png)


There is no help for this function.

**Comment by power4454** [comment]
Now it is solved.
