### ISSUE TITLE
신규 템플릿에 샘플 데이터가 없습니다. 

### ISSUE THREAD

**Issue by krazyeom** [brightics/studio#757]
java.lang.Exception: OSError: Passed non-file path: /brightics-studio/brightics-server/data/brightics@samsung.com/upload/stateoftheunion.csv

java.lang.Exception: OSError: Passed non-file path: /brightics-studio/brightics-server/data/brightics@samsung.com/upload/abalone.csv

java.lang.Exception: OSError: Passed non-file path: /brightics-studio/brightics-server/data/brightics@samsung.com/upload/income.csv

템플릿에 대한 데이터는 https://github.com/brightics/studio/tree/master/api-server/brightics-server/data 에 넣어야 합니다.

**Comment by hyoxt121** [comment]
업로드 완료되었습니다

**Comment by krazyeom** [comment]
데이터 입력 이후 잘 돌아가던 iris 조차 돌아가지 않습니다. 

뿐만 아니라 메이븐 빌드시 데이터에 관한 brightics.db 추가 과정정도 필요해보입니다. 

예전에 이 문제로 template 에 직접 넣지 못하는 문제가 있었습니다. 

1. 메이븐 빌드시 brightics.db 추가 프로세스 추가 또는 
2. git에서 template 삭제 후, 빌드 서버에서 빌드시 template 추가

둘중에 괜찮은 방법으로 template 을 추가해야합니다. 

지금 방법으로는 portable download 방식에는 문제가 없지만, 소스 빌드해서 사용하면 문제가 있습니다.
