### ISSUE TITLE
튜토리얼 문의

### ISSUE THREAD

**Issue by helper4u** [brightics/studio#773]
안녕하세요 ?
튜토리얼을 가지고 테스트하고있는데요
json을 import 하면 해당 function이 없다고 합니다 
예를 들면,  Pre-processing의 데이터 결합 "06_preprocessing_join.json"을 import하면 첨부파일처럼 에러가 발생합니다.

그리고,  studio를 깔아서 튜토리얼데로 하면 없는 Type Cast 등 없는 함수가 있는데 왜그럴까요 ? 

![Error](https://user-images.githubusercontent.com/23555777/86482657-63408f80-bd20-11ea-9701-c9c55f071307.PNG)

**Comment by hyoxt121** [comment]
안녕하세요.
아마 Enterprise용 튜토리얼(주로 Spark 함수 사용)을 가지고 Studio에 import를 하셨을 가능성이 큽니다. 튜토리얼 버전을 다시 한번 확인해보시기 바랍니다.
