### ISSUE TITLE
Cannot execute python process. Failed to start external python process.

### ISSUE THREAD

**Issue by wankeecho** [brightics/studio#788]
studio 1.1 다운로드 받았고
exe 파일을 눌러 설치를 진행하였습니다.

start-brightics.cmd 를 실행하여 방화벽 허용 후 시작하려는 중에
python process 에서 Not ready 상태로 시작된 탓인지 

Load 단계에서 "Cannot execute python process. Failed to start external python process."
가 나오며 Load 실패 하였습니다

path 가 꼬이거나 한 것 같은데.. 해결 방법이 있을까요?
/brightics-studio/lib/python 폴더 내 python.exe는 커맨드 창으로 떠서 3.6.6 버전으로 실행이 
되는 것은 확인하였습니다.

Active directory 설치로 환경변수 설정이 엉망이 된 탓인지..
path 설정을 알려주시는 등 방법을 알려주시면 감사하겠습니다..

**Comment by krazyeom** [comment]
start-brightics.cmd 로 시작하는데 python process 에서 Not ready 상태가 나오나요?
