### ISSUE TITLE
Can't do 'start all service' from Brightics Studio Launcher

### ISSUE THREAD

**Issue by jedi-lee24** [brightics/studio#792]
Brightics Studio Launcher don't proceed from below status.

![Brightics studio launcher](https://user-images.githubusercontent.com/68832655/88495836-189bf580-cff6-11ea-855c-b6d8e6002614.JPG)

**Comment by krazyeom** [comment]
Could you send me a detail log of brightics server on brightics-studio\brightics-server\logs

**Comment by krazyeom** [comment]
I'm closing this issue for now. If you have an issue to report, feel free to reopen.
