### ISSUE TITLE
brightics 설치 시 계속 다시시작하기가 됩니다.

### ISSUE THREAD

**Issue by jiyeon1119** [brightics/studio#799]
브라이틱스 설치를 하려고 windows에서 exe 파일을 시작하려 하면 계속 PC에 문제가 있다는 파란 창이 뜨면서 PC가 다시시작됩니다.
Windows 10에서는 설치가 되지 않는것인가요?
답변 부탁드리겠습니다.

**Comment by krazyeom** [comment]
혹시 삼성 SDS 분이신가요? 
knoxdrive 에 설치하셨다면 network 드라이브가 아닌 곳에 설치 부탁드립니다.
