### ISSUE TITLE
Studio 오른쪽 화면 blank issue

### ISSUE THREAD

**Issue by helper4u** [brightics/studio#805]
안녕하세요 ?

갑자기 studio를 사용중인데 모든 화면에서 오른쪽에 blank로 나오는 이유가 무엇일까요 ?
조치 방법좀 알려주세요.   감사합니다

![Brightics Issue](https://user-images.githubusercontent.com/23555777/91059724-15495900-e5f8-11ea-89ee-eb0fc0b87ed1.PNG)

**Comment by krazyeom** [comment]
7월 버전에서 해결되었으며, 기존 버전에서는 화면 비율을 100%로 해서 사용하면 됩니다.
