### ISSUE TITLE
Profile Table 실행 결과 Correlations에서 한글 깨짐 현상

### ISSUE THREAD

**Issue by phs-lab** [brightics/studio#808]
안녕하십니까?

Profile Table을 실행했는데, Correlations 부분에서 그래프 축의 Label이 깨져서 나타납니다.
아마도 Data에 한글값이 있어서 그런 것 같은데, 오른쪽 영역의 다른 부분에서는 정상인데,
Correlations부분만 깨지는 현상이 있습니다.

![Profile Table 실행 결과 Correlations에서 한글 깨짐 현상](https://user-images.githubusercontent.com/59041349/91508354-44224080-e912-11ea-91c5-72e81144e878.PNG)

**Comment by krazyeom** [comment]
brightics-studio\lib\python\Lib\site-packages\pandas_profiling\pandas_profiling.mplstyle 

27라인을 아래와 같이 변경을 하면 한글이 잘 나오는 것을 확인할 수 있습니다.
```
font.sans-serif: Malgun Gothic, Arial, Liberation Sans, Bitstream Vera Sans, sans-serif
```
![image](https://user-images.githubusercontent.com/442477/91532100-c7f71f80-e948-11ea-8bb2-9108494e52e3.png)

다음 버전 릴리스때 패치 예정입니다.
