### ISSUE TITLE
[BUG] docker version is not running

### ISSUE THREAD

**Issue by acras9** [brightics/studio#811]
**Describe the bug**
When i tried to Run the Load file , it;s not extcuted wtih python error on docker version

**Comment by krazyeom** [comment]
Thanks for reporting issue. 
I've just found missing `pip install -r requirements.txt` command on the Dockerfile.
I'm building and testing it now. When a Docker version is released, I will inform you here.

**Comment by krazyeom** [comment]
It works now on docker.
