### ISSUE TITLE
MAC 에서 추가 패키지 설치 어떻게 하나요?

### ISSUE THREAD

**Issue by slpmee** [brightics/studio#817]
/brightics-studio/lib/python/python get-pip.py : This step is only needed once.
/brightics-studio/lib/python/Scripts/pip install <ANY_PACKAGES>

스튜디오 최신버전 3월 초에 설치한 분이고 패키지 설치가 안된다는 문의가 있어서 위와 같이 해보라고 했는데요
lib 내에 python 폴더가 없습니다. brightics_python_env (?) 라는 폴더만 있고요.

다른 방법이 있는건가요? 알려주세요~

**Comment by krazyeom** [comment]
brightics_python_env 가 python 환경 부분입니다. 참고해서 설치하시면 됩니다.
