### ISSUE TITLE
[BUG] MAC 에서 추가패키지 설치 재문의

### ISSUE THREAD

**Issue by slpmee** [brightics/studio#818]
MAC 사용하는 다른사람한테 python env 들어가서 이 방법 동일하게 하면 된다고 가이드를 했는데
잘 모르겠다고 하는데요..
/brightics-studio/lib/python/python get-pip.py : This step is only needed once.
/brightics-studio/lib/python/Scripts/pip install <ANY_PACKAGES>

아래 그림에서 두번째 그림의 pip 이용해서 install 하면 되는건가요? 
캡처를 받아온거라 그림이 불충분합니다. ㅜ 

![image](https://user-images.githubusercontent.com/18569006/112616524-319bc580-8e67-11eb-9e00-d447215b4ca7.png)
![image](https://user-images.githubusercontent.com/18569006/112616597-4415ff00-8e67-11eb-8bed-8d5dc11041d9.png)
![image](https://user-images.githubusercontent.com/18569006/112616636-4f692a80-8e67-11eb-8786-df3805675007.png)

**Comment by krazyeom** [comment]
공식적으로는 다른 패키지 설치를 지원하고 있지 않습니다. 그래서 get-pip가 없을수 있습니다. 
윈도 버전으로 가이드 해드리는거입니다.

pip 는 구글링해서 pip 패키지를 설치해서 사용하시면 됩니다. 

그리고 최소한 shell 스크립트 사용법은 아셔야할 것 같습니다. 
./python 과 python 의 차이를 모르시는 것 같네요.

**Comment by slpmee** [comment]
브라이틱스 처음 사용하는 분들이 초보일 수 밖에 없는데 ...   
그러면 깃헙에 있는 인스톨 가이드에 윈도우 버전 가이드라고 안내가 되어야할 것 같습니다. 인스톨 가이드에서 공식적으로 안내를 하고 있는데 그 방법으로 다른 OS 는 안된다고 하면 한줄 코멘트라도 있어야 사용자들이 알아서 구글링이라도 할 듯 합니다.

**Comment by krazyeom** [comment]
추가 페이키 설치시 문제가 되는게 많아서, 관련하여 인스톨링 가이드에서 삭제했습니다.

**Comment by krazyeom** [comment]
크게 2단계만 진행하면 됩니다. 단, 이후 발생하는 라이브러리 디펜던시 이슈는 책임지지 않습니다. 

1. brightics studio 파이선 내에서 pip를 설치한다. 
2. brightics 파이선 내의 설치된 pip로 패치지를 설치한다.
