### ISSUE TITLE
Data Load(Python)시 오류 발생

### ISSUE THREAD

**Issue by shbeat** [brightics/studio#822]
3.7버전에서는 input file Load(파란색) 기능이 이상 없었습니다.
하지만 이번에 업데이트 된 버전 Welcome to Brightics AI v3.8에서 데이터 로드 오류가 발생되어 이슈를 남깁니다.

Brightics에서 input파일 Data Load(파란색 아이콘 Python)시 아래와 같은 오류가 발생합니다.
Python Resources
Failed to get resource information. Please try again.
빨간색 아이콘 Data Load(Spark)로 데이터 로드는 가능하나, 실제 DS 시험 응시 버전과 맞지 않아서 그렇습니다.
접속URL은 아래와 같습니다.
https://trialml.brightics.ai/home
Welcome to Brightics AI v3.8
이럴 경우 어떻게 해결해야 할지 답변 부탁드립니다.
shbeat2@naver.com

**Comment by krazyeom** [comment]
Brightics Studio 와 관련되지 않는 이슈입니다. 
관련 이슈는 brightics.cs@samsung.com 으로 문의하세요.
