### ISSUE TITLE
[BUG] 프로그램 설치 및 실행이 안됩니다.

### ISSUE THREAD

**Issue by Jo-HJ** [brightics/studio#827]
다음과 같은 메시지와 함께 프로그램 설치 및 실행이 안됩니다.

이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.ComponentModel.Win32Exception (0x80004005): 요청한 작업을 수행하려면 권한 상승이 필요합니다
   위치: System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   위치: System.Diagnostics.Process.Start()
   위치: System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   위치: Brightics_Studio_Launcher.Brightics_Studio_Launcher.StartServiceWithServiceName(Services service)
   위치: Brightics_Studio_Launcher.Brightics_Studio_Launcher.StartStopBrighticsServerButton_Click(Object sender, EventArgs e)
   위치: Brightics_Studio_Launcher.Brightics_Studio_Launcher.MLStartAllServiceButton_Click(Object sender, EventArgs e)
   위치: System.Windows.Forms.Control.OnClick(EventArgs e)
   위치: System.Windows.Forms.Button.OnClick(EventArgs e)
   위치: System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   위치: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   위치: System.Windows.Forms.Control.WndProc(Message& m)
   위치: System.Windows.Forms.ButtonBase.WndProc(Message& m)
   위치: System.Windows.Forms.Button.WndProc(Message& m)
   위치: System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   위치: System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4400.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Brightics-Studio-Launcher
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/brightics-studio/brightics-studio/Brightics-Studio-Launcher.exe
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4400.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4360.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4390.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4190.0 built by: NET48REL1LAST_B
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4390.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 디버깅 **************
JIT(Just In Time) 디버깅을 사용하려면 이 응용 프로그램 또는 컴퓨터의
config 파일(machine.config)의 jitDebugging 값을 
system.windows.forms 섹션에 설정해야 합니다.
또한 응용 프로그램은 디버깅할 수 있도록 컴파일되어야
합니다.

예:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT 디버깅을 사용하면 처리되지 않은 모든 예외는
이 대화 상자에서 처리되지 않고 컴퓨터에 등록된 JIT 
디버거에 보내집니다.

the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Version 2004, macOS, linux]
 - Version [e.g. 2020.07.21]

**Additional context**

**Comment by gyu77hs** [comment]
작성해 주신 본문에 OS나 설치를 진행하신 Studio의 버전이 명시되어 있지 않아, 정확한 안내 및 판단이 어려우나, 권한 문제로 보여집니다.

* 설치 시, 설치 파일을 [관리자 권한으로 실행] 하여 설치 하시거나 Brightics-Studio-Launcher.exe 파일을 [관리자 권한으로 실행] 하여 진행 해보시기 바랍니다.

* 또는 권한이 제한적인 위치에서 실행하시어 발생하는 문제일 수도 있으므로, 설치 위치를 바꾸어( ex: D:/brightics-studio) 진행 해보시기 바랍니다.

* 그럼에도 설치 및 실행이 불가한 경우 .Net Framework 충돌 및 버전 문제로 인한 발생일 수 있으니, OS에 맞는 .Net Framework 재설치가 필요할 수도 있을 듯 합니다. 댓글로 환경에 대한 정보를 주시면 참고하여 설치 가능한 버전 및 Link를 전달 드리도록 하겠습니다.

**Comment by Jo-HJ** [comment]
Windows10입니다. 

관리자권한으로 실행으로 Brightics-Studio-Launcher.exe파일을 실행하자 해결됐습니다.

감사합니다.
