### ISSUE TITLE
[BUG] 재설치 시 이전에 선택한 언어를 변경하여도 계속 첫 설치 시 선택한 언어만 설치됨

### ISSUE THREAD

**Issue by cwjeon48** [brightics/studio#856]
**Describe the bug**
재설치 시 이전에 선택한 언어를 변경하여도 계속 첫 설치 시 선택한 언어만 설치됨

**To Reproduce**
한국어를 선택하고 설치한 후 언인스톨
다시 설치하며 영어 선택하여도 계속 한국어로 나타남

**Expected behavior**
제거 후 재설치 시에 언어 선택 가능해야 함

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser 크롬
 - Version 106.0.5249.119

**Additional context**

**Comment by gyu77hs** [comment]
설치 시점의 언어 선택은 Install 과정에 제공되는 언어를 선택하는 것입니다. 설치 후 default 언어는 한국어로 제공 되며, 우측 상단 톱니바퀴 [Settings] > [속성 변경 - 이동] > [일반] > [언어] 에서 영문으로 변경 가능합니다.

**Comment by cwjeon48** [comment]
빠른 회신 감사합니다.
다만, 설치 시에 언어 선택에 혼선이 생길 수 있는 점을 보완하면 좋을 듯 합니다.
